/*
 * This file was last modified at 2026.05.08 19:33 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * EntityModelResourceRecordView.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import su.svn.lib.core.model.Link;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * EntityModelResourceRecordView
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-08T19:23:51.960842+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class EntityModelResourceRecordView {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @javax.annotation.Nullable
  private Boolean visible;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @javax.annotation.Nullable
  private Integer flags;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @javax.annotation.Nullable
  private UUID parentId;

  public static final String SERIALIZED_NAME_USER_NAME = "userName";
  @SerializedName(SERIALIZED_NAME_USER_NAME)
  @javax.annotation.Nullable
  private String userName;

  public static final String SERIALIZED_NAME_POST_AT = "postAt";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  @javax.annotation.Nullable
  private OffsetDateTime postAt;

  public static final String SERIALIZED_NAME_REFRESH_AT = "refreshAt";
  @SerializedName(SERIALIZED_NAME_REFRESH_AT)
  @javax.annotation.Nullable
  private OffsetDateTime refreshAt;

  public static final String SERIALIZED_NAME_LAST_CHANGED_TIME = "lastChangedTime";
  @SerializedName(SERIALIZED_NAME_LAST_CHANGED_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime lastChangedTime;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_JSON = "json";
  @SerializedName(SERIALIZED_NAME_JSON)
  @javax.annotation.Nullable
  private Map<String, String> json = new HashMap<>();

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nullable
  private Map<String, Link> links = new HashMap<>();

  public EntityModelResourceRecordView() {
  }

  public EntityModelResourceRecordView id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public EntityModelResourceRecordView visible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @javax.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public EntityModelResourceRecordView flags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @javax.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
  }


  public EntityModelResourceRecordView parentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nullable
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
  }


  public EntityModelResourceRecordView userName(@javax.annotation.Nullable String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   */
  @javax.annotation.Nullable
  public String getUserName() {
    return userName;
  }

  public void setUserName(@javax.annotation.Nullable String userName) {
    this.userName = userName;
  }


  public EntityModelResourceRecordView postAt(@javax.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
    return this;
  }

  /**
   * Get postAt
   * @return postAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPostAt() {
    return postAt;
  }

  public void setPostAt(@javax.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
  }


  public EntityModelResourceRecordView refreshAt(@javax.annotation.Nullable OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
    return this;
  }

  /**
   * Get refreshAt
   * @return refreshAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRefreshAt() {
    return refreshAt;
  }

  public void setRefreshAt(@javax.annotation.Nullable OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
  }


  public EntityModelResourceRecordView lastChangedTime(@javax.annotation.Nullable OffsetDateTime lastChangedTime) {
    this.lastChangedTime = lastChangedTime;
    return this;
  }

  /**
   * Get lastChangedTime
   * @return lastChangedTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastChangedTime() {
    return lastChangedTime;
  }

  public void setLastChangedTime(@javax.annotation.Nullable OffsetDateTime lastChangedTime) {
    this.lastChangedTime = lastChangedTime;
  }


  public EntityModelResourceRecordView title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public EntityModelResourceRecordView json(@javax.annotation.Nullable Map<String, String> json) {
    this.json = json;
    return this;
  }

  public EntityModelResourceRecordView putJsonItem(String key, String jsonItem) {
    if (this.json == null) {
      this.json = new HashMap<>();
    }
    this.json.put(key, jsonItem);
    return this;
  }

  /**
   * Get json
   * @return json
   */
  @javax.annotation.Nullable
  public Map<String, String> getJson() {
    return json;
  }

  public void setJson(@javax.annotation.Nullable Map<String, String> json) {
    this.json = json;
  }


  public EntityModelResourceRecordView tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public EntityModelResourceRecordView addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public EntityModelResourceRecordView links(@javax.annotation.Nullable Map<String, Link> links) {
    this.links = links;
    return this;
  }

  public EntityModelResourceRecordView putLinksItem(String key, Link linksItem) {
    if (this.links == null) {
      this.links = new HashMap<>();
    }
    this.links.put(key, linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @javax.annotation.Nullable
  public Map<String, Link> getLinks() {
    return links;
  }

  public void setLinks(@javax.annotation.Nullable Map<String, Link> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityModelResourceRecordView entityModelResourceRecordView = (EntityModelResourceRecordView) o;
    return Objects.equals(this.id, entityModelResourceRecordView.id) &&
        Objects.equals(this.visible, entityModelResourceRecordView.visible) &&
        Objects.equals(this.flags, entityModelResourceRecordView.flags) &&
        Objects.equals(this.parentId, entityModelResourceRecordView.parentId) &&
        Objects.equals(this.userName, entityModelResourceRecordView.userName) &&
        Objects.equals(this.postAt, entityModelResourceRecordView.postAt) &&
        Objects.equals(this.refreshAt, entityModelResourceRecordView.refreshAt) &&
        Objects.equals(this.lastChangedTime, entityModelResourceRecordView.lastChangedTime) &&
        Objects.equals(this.title, entityModelResourceRecordView.title) &&
        Objects.equals(this.json, entityModelResourceRecordView.json) &&
        Objects.equals(this.tags, entityModelResourceRecordView.tags) &&
        Objects.equals(this.links, entityModelResourceRecordView.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, visible, flags, parentId, userName, postAt, refreshAt, lastChangedTime, title, json, tags, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityModelResourceRecordView {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    refreshAt: ").append(toIndentedString(refreshAt)).append("\n");
    sb.append("    lastChangedTime: ").append(toIndentedString(lastChangedTime)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "visible", "flags", "parentId", "userName", "postAt", "refreshAt", "lastChangedTime", "title", "json", "tags", "_links"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EntityModelResourceRecordView
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EntityModelResourceRecordView.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EntityModelResourceRecordView is not found in the empty JSON string", EntityModelResourceRecordView.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EntityModelResourceRecordView.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EntityModelResourceRecordView` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("parentId") != null && !jsonObj.get("parentId").isJsonNull()) && !jsonObj.get("parentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentId").toString()));
      }
      if ((jsonObj.get("userName") != null && !jsonObj.get("userName").isJsonNull()) && !jsonObj.get("userName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `userName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userName").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EntityModelResourceRecordView.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EntityModelResourceRecordView' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EntityModelResourceRecordView> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EntityModelResourceRecordView.class));

       return (TypeAdapter<T>) new TypeAdapter<EntityModelResourceRecordView>() {
           @Override
           public void write(JsonWriter out, EntityModelResourceRecordView value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EntityModelResourceRecordView read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EntityModelResourceRecordView given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EntityModelResourceRecordView
   * @throws IOException if the JSON string is invalid with respect to EntityModelResourceRecordView
   */
  public static EntityModelResourceRecordView fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EntityModelResourceRecordView.class);
  }

  /**
   * Convert an instance of EntityModelResourceRecordView to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

