/*
 * This file was last modified at 2026.05.08 19:33 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * NewJsonRecord.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * NewJsonRecord
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-08T19:23:51.960842+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class NewJsonRecord {
  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @javax.annotation.Nullable
  private Boolean visible;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @javax.annotation.Nullable
  private Integer flags;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @javax.annotation.Nonnull
  private UUID parentId = new UUID(0, 0);

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_JSON = "json";
  @SerializedName(SERIALIZED_NAME_JSON)
  @javax.annotation.Nullable
  private Map<String, String> json = new HashMap<>();

  public static final String SERIALIZED_NAME_POST_AT = "postAt";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime postAt;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Set<String> tags = new LinkedHashSet<>();

  public NewJsonRecord() {
  }

  public NewJsonRecord visible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @javax.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public NewJsonRecord flags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @javax.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
  }


  public NewJsonRecord parentId(@javax.annotation.Nonnull UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nonnull
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(@javax.annotation.Nonnull UUID parentId) {
    this.parentId = parentId;
  }


  public NewJsonRecord title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public NewJsonRecord json(@javax.annotation.Nullable Map<String, String> json) {
    this.json = json;
    return this;
  }

  public NewJsonRecord putJsonItem(String key, String jsonItem) {
    if (this.json == null) {
      this.json = new HashMap<>();
    }
    this.json.put(key, jsonItem);
    return this;
  }

  /**
   * Get json
   * @return json
   */
  @javax.annotation.Nullable
  public Map<String, String> getJson() {
    return json;
  }

  public void setJson(@javax.annotation.Nullable Map<String, String> json) {
    this.json = json;
  }


  public NewJsonRecord postAt(@javax.annotation.Nonnull OffsetDateTime postAt) {
    this.postAt = postAt;
    return this;
  }

  /**
   * Get postAt
   * @return postAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getPostAt() {
    return postAt;
  }

  public void setPostAt(@javax.annotation.Nonnull OffsetDateTime postAt) {
    this.postAt = postAt;
  }


  public NewJsonRecord tags(@javax.annotation.Nullable Set<String> tags) {
    this.tags = tags;
    return this;
  }

  public NewJsonRecord addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public Set<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Set<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewJsonRecord newJsonRecord = (NewJsonRecord) o;
    return Objects.equals(this.visible, newJsonRecord.visible) &&
        Objects.equals(this.flags, newJsonRecord.flags) &&
        Objects.equals(this.parentId, newJsonRecord.parentId) &&
        Objects.equals(this.title, newJsonRecord.title) &&
        Objects.equals(this.json, newJsonRecord.json) &&
        Objects.equals(this.postAt, newJsonRecord.postAt) &&
        Objects.equals(this.tags, newJsonRecord.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(visible, flags, parentId, title, json, postAt, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewJsonRecord {\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("visible", "flags", "parentId", "title", "json", "postAt", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("parentId", "postAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NewJsonRecord
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NewJsonRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NewJsonRecord is not found in the empty JSON string", NewJsonRecord.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NewJsonRecord.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `NewJsonRecord` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NewJsonRecord.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("parentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentId").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NewJsonRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NewJsonRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NewJsonRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NewJsonRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<NewJsonRecord>() {
           @Override
           public void write(JsonWriter out, NewJsonRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NewJsonRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NewJsonRecord given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NewJsonRecord
   * @throws IOException if the JSON string is invalid with respect to NewJsonRecord
   */
  public static NewJsonRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NewJsonRecord.class);
  }

  /**
   * Convert an instance of NewJsonRecord to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

