/*
 * This file was last modified at 2026.04.04 15:56 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * ResourceJsonRecord.java
 * $Id$
 */

/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import su.svn.lib.core.JSON;

/**
 * ResourceJsonRecord
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-04T15:39:52.250208+03:00[Europe/Moscow]", comments = "Generator version: 7.21.0")
public class ResourceJsonRecord {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  @javax.annotation.Nullable
  private UUID parentId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  @javax.annotation.Nullable
  private Map<String, String> values = new HashMap<>();

  public static final String SERIALIZED_NAME_POST_AT = "postAt";
  @SerializedName(SERIALIZED_NAME_POST_AT)
  @javax.annotation.Nullable
  private OffsetDateTime postAt;

  public static final String SERIALIZED_NAME_REFRESH_AT = "refreshAt";
  @SerializedName(SERIALIZED_NAME_REFRESH_AT)
  @javax.annotation.Nullable
  private OffsetDateTime refreshAt;

  public static final String SERIALIZED_NAME_VISIBLE = "visible";
  @SerializedName(SERIALIZED_NAME_VISIBLE)
  @javax.annotation.Nullable
  private Boolean visible;

  public static final String SERIALIZED_NAME_FLAGS = "flags";
  @SerializedName(SERIALIZED_NAME_FLAGS)
  @javax.annotation.Nullable
  private Integer flags;

  public ResourceJsonRecord() {
  }

  public ResourceJsonRecord id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public ResourceJsonRecord parentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nullable
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(@javax.annotation.Nullable UUID parentId) {
    this.parentId = parentId;
  }


  public ResourceJsonRecord title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public ResourceJsonRecord values(@javax.annotation.Nullable Map<String, String> values) {
    this.values = values;
    return this;
  }

  public ResourceJsonRecord putValuesItem(String key, String valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @javax.annotation.Nullable
  public Map<String, String> getValues() {
    return values;
  }

  public void setValues(@javax.annotation.Nullable Map<String, String> values) {
    this.values = values;
  }


  public ResourceJsonRecord postAt(@javax.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
    return this;
  }

  /**
   * Get postAt
   * @return postAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getPostAt() {
    return postAt;
  }

  public void setPostAt(@javax.annotation.Nullable OffsetDateTime postAt) {
    this.postAt = postAt;
  }


  public ResourceJsonRecord refreshAt(@javax.annotation.Nullable OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
    return this;
  }

  /**
   * Get refreshAt
   * @return refreshAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRefreshAt() {
    return refreshAt;
  }

  public void setRefreshAt(@javax.annotation.Nullable OffsetDateTime refreshAt) {
    this.refreshAt = refreshAt;
  }


  public ResourceJsonRecord visible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
    return this;
  }

  /**
   * Get visible
   * @return visible
   */
  @javax.annotation.Nullable
  public Boolean getVisible() {
    return visible;
  }

  public void setVisible(@javax.annotation.Nullable Boolean visible) {
    this.visible = visible;
  }


  public ResourceJsonRecord flags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
    return this;
  }

  /**
   * Get flags
   * @return flags
   */
  @javax.annotation.Nullable
  public Integer getFlags() {
    return flags;
  }

  public void setFlags(@javax.annotation.Nullable Integer flags) {
    this.flags = flags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceJsonRecord resourceJsonRecord = (ResourceJsonRecord) o;
    return Objects.equals(this.id, resourceJsonRecord.id) &&
        Objects.equals(this.parentId, resourceJsonRecord.parentId) &&
        Objects.equals(this.title, resourceJsonRecord.title) &&
        Objects.equals(this.values, resourceJsonRecord.values) &&
        Objects.equals(this.postAt, resourceJsonRecord.postAt) &&
        Objects.equals(this.refreshAt, resourceJsonRecord.refreshAt) &&
        Objects.equals(this.visible, resourceJsonRecord.visible) &&
        Objects.equals(this.flags, resourceJsonRecord.flags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parentId, title, values, postAt, refreshAt, visible, flags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceJsonRecord {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    refreshAt: ").append(toIndentedString(refreshAt)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "parentId", "title", "values", "postAt", "refreshAt", "visible", "flags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResourceJsonRecord
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResourceJsonRecord.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ResourceJsonRecord is not found in the empty JSON string", ResourceJsonRecord.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResourceJsonRecord.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ResourceJsonRecord` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("parentId") != null && !jsonObj.get("parentId").isJsonNull()) && !jsonObj.get("parentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `parentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentId").toString()));
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResourceJsonRecord.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResourceJsonRecord' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResourceJsonRecord> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResourceJsonRecord.class));

       return (TypeAdapter<T>) new TypeAdapter<ResourceJsonRecord>() {
           @Override
           public void write(JsonWriter out, ResourceJsonRecord value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResourceJsonRecord read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResourceJsonRecord given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResourceJsonRecord
   * @throws IOException if the JSON string is invalid with respect to ResourceJsonRecord
   */
  public static ResourceJsonRecord fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResourceJsonRecord.class);
  }

  /**
   * Convert an instance of ResourceJsonRecord to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

