// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_has_roles

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserHasRole struct {
	ID          int64            `json:"id"`
	UserName    pgtype.Text      `json:"user_name"`
	Role        pgtype.Text      `json:"role"`
	CreateTime  pgtype.Timestamp `json:"create_time"`
	UpdateTime  pgtype.Timestamp `json:"update_time"`
	Enabled     pgtype.Bool      `json:"enabled"`
	LocalChange bool             `json:"local_change"`
	Visible     pgtype.Bool      `json:"visible"`
	Flags       int32            `json:"flags"`
}
