/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedModelEntityModelResourceRecordView {
    #[serde(rename = "_embedded", skip_serializing_if = "Option::is_none")]
    pub _embedded: Option<Box<models::PagedModelEntityModelResourceRecordViewEmbedded>>,
    #[serde(rename = "_links", skip_serializing_if = "Option::is_none")]
    pub _links: Option<std::collections::HashMap<String, models::Link>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageMetadata>>,
}

impl PagedModelEntityModelResourceRecordView {
    pub fn new() -> PagedModelEntityModelResourceRecordView {
        PagedModelEntityModelResourceRecordView {
            _embedded: None,
            _links: None,
            page: None,
        }
    }
}

