/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedModelEntityModelResourceRecordViewEmbedded {
    #[serde(rename = "resourceRecordViewList", skip_serializing_if = "Option::is_none")]
    pub resource_record_view_list: Option<Vec<models::EntityModelResourceRecordView>>,
}

impl PagedModelEntityModelResourceRecordViewEmbedded {
    pub fn new() -> PagedModelEntityModelResourceRecordViewEmbedded {
        PagedModelEntityModelResourceRecordViewEmbedded {
            resource_record_view_list: None,
        }
    }
}

