/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceRecordViewFilter {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "fromTime", skip_serializing_if = "Option::is_none")]
    pub from_time: Option<String>,
    #[serde(rename = "fromDate", skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    #[serde(rename = "withDisabled", skip_serializing_if = "Option::is_none")]
    pub with_disabled: Option<bool>,
}

impl ResourceRecordViewFilter {
    pub fn new() -> ResourceRecordViewFilter {
        ResourceRecordViewFilter {
            title: None,
            from_time: None,
            from_date: None,
            to_date: None,
            with_disabled: None,
        }
    }
}

