/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceJsonRecord {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<uuid::Uuid>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "postAt", skip_serializing_if = "Option::is_none")]
    pub post_at: Option<String>,
    #[serde(rename = "refreshAt", skip_serializing_if = "Option::is_none")]
    pub refresh_at: Option<String>,
}

impl ResourceJsonRecord {
    pub fn new() -> ResourceJsonRecord {
        ResourceJsonRecord {
            id: None,
            visible: None,
            flags: None,
            parent_id: None,
            title: None,
            values: None,
            post_at: None,
            refresh_at: None,
        }
    }
}

