/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateJsonRecord {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "parentId")]
    pub parent_id: uuid::Uuid,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "postAt", skip_serializing_if = "Option::is_none")]
    pub post_at: Option<String>,
    #[serde(rename = "refreshAt")]
    pub refresh_at: String,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl UpdateJsonRecord {
    pub fn new(id: uuid::Uuid, parent_id: uuid::Uuid, refresh_at: String) -> UpdateJsonRecord {
        UpdateJsonRecord {
            id,
            parent_id,
            title: None,
            json: None,
            post_at: None,
            refresh_at,
            visible: None,
            flags: None,
            tags: None,
        }
    }
}

