# coding: utf-8

# flake8: noqa
"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from core.model.entity_model_resource_record_view import EntityModelResourceRecordView
from core.model.error_response import ErrorResponse
from core.model.link import Link
from core.model.new_json_record import NewJsonRecord
from core.model.page_metadata import PageMetadata
from core.model.pageable import Pageable
from core.model.paged_model_entity_model_resource_record_view import PagedModelEntityModelResourceRecordView
from core.model.paged_model_entity_model_resource_record_view_embedded import PagedModelEntityModelResourceRecordViewEmbedded
from core.model.resource_json_record import ResourceJsonRecord
from core.model.resource_record_view_filter import ResourceRecordViewFilter
from core.model.update_json_record import UpdateJsonRecord

