# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from core.models.link import Link
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EntityModelResourceRecordView(BaseModel):
    """
    EntityModelResourceRecordView
    """ # noqa: E501
    id: Optional[UUID] = None
    visible: Optional[StrictBool] = None
    flags: Optional[StrictInt] = None
    parent_id: Optional[UUID] = Field(default=None, alias="parentId")
    user_name: Optional[StrictStr] = Field(default=None, alias="userName")
    post_at: Optional[datetime] = Field(default=None, alias="postAt")
    refresh_at: Optional[datetime] = Field(default=None, alias="refreshAt")
    last_changed_time: Optional[datetime] = Field(default=None, alias="lastChangedTime")
    title: Optional[StrictStr] = None
    var_json: Optional[Dict[str, StrictStr]] = Field(default=None, alias="json")
    tags: Optional[List[StrictStr]] = None
    links: Optional[Dict[str, Link]] = Field(default=None, alias="_links")
    __properties: ClassVar[List[str]] = ["id", "visible", "flags", "parentId", "userName", "postAt", "refreshAt", "lastChangedTime", "title", "json", "tags", "_links"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EntityModelResourceRecordView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in links (dict)
        _field_dict = {}
        if self.links:
            for _key_links in self.links:
                if self.links[_key_links]:
                    _field_dict[_key_links] = self.links[_key_links].to_dict()
            _dict['_links'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EntityModelResourceRecordView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "visible": obj.get("visible"),
            "flags": obj.get("flags"),
            "parentId": obj.get("parentId"),
            "userName": obj.get("userName"),
            "postAt": obj.get("postAt"),
            "refreshAt": obj.get("refreshAt"),
            "lastChangedTime": obj.get("lastChangedTime"),
            "title": obj.get("title"),
            "json": obj.get("json"),
            "tags": obj.get("tags"),
            "_links": dict(
                (_k, Link.from_dict(_v))
                for _k, _v in obj["_links"].items()
            )
            if obj.get("_links") is not None
            else None
        })
        return _obj


