/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Link from './Link';

/**
 * The EntityModelResourceRecordView model module.
 * @module su.svn.lib.core.model/EntityModelResourceRecordView
 * @version v0
 */
class EntityModelResourceRecordView {
    /**
     * Constructs a new <code>EntityModelResourceRecordView</code>.
     * @alias module:su.svn.lib.core.model/EntityModelResourceRecordView
     */
    constructor() { 
        
        EntityModelResourceRecordView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntityModelResourceRecordView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/EntityModelResourceRecordView} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/EntityModelResourceRecordView} The populated <code>EntityModelResourceRecordView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityModelResourceRecordView();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], 'Number');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('postAt')) {
                obj['postAt'] = ApiClient.convertToType(data['postAt'], 'Date');
            }
            if (data.hasOwnProperty('refreshAt')) {
                obj['refreshAt'] = ApiClient.convertToType(data['refreshAt'], 'Date');
            }
            if (data.hasOwnProperty('lastChangedTime')) {
                obj['lastChangedTime'] = ApiClient.convertToType(data['lastChangedTime'], 'Date');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], {'String': 'String'});
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': Link});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityModelResourceRecordView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityModelResourceRecordView</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
EntityModelResourceRecordView.prototype['id'] = undefined;

/**
 * @member {Boolean} visible
 */
EntityModelResourceRecordView.prototype['visible'] = undefined;

/**
 * @member {Number} flags
 */
EntityModelResourceRecordView.prototype['flags'] = undefined;

/**
 * @member {String} parentId
 */
EntityModelResourceRecordView.prototype['parentId'] = undefined;

/**
 * @member {String} userName
 */
EntityModelResourceRecordView.prototype['userName'] = undefined;

/**
 * @member {Date} postAt
 */
EntityModelResourceRecordView.prototype['postAt'] = undefined;

/**
 * @member {Date} refreshAt
 */
EntityModelResourceRecordView.prototype['refreshAt'] = undefined;

/**
 * @member {Date} lastChangedTime
 */
EntityModelResourceRecordView.prototype['lastChangedTime'] = undefined;

/**
 * @member {String} title
 */
EntityModelResourceRecordView.prototype['title'] = undefined;

/**
 * @member {Object.<String, String>} values
 */
EntityModelResourceRecordView.prototype['values'] = undefined;

/**
 * @member {Object.<String, module:su.svn.lib.core.model/Link>} _links
 */
EntityModelResourceRecordView.prototype['_links'] = undefined;






export default EntityModelResourceRecordView;

