/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewJsonRecord model module.
 * @module su.svn.lib.core.model/NewJsonRecord
 * @version v0
 */
class NewJsonRecord {
    /**
     * Constructs a new <code>NewJsonRecord</code>.
     * @alias module:su.svn.lib.core.model/NewJsonRecord
     * @param parentId {String} 
     * @param postAt {Date} 
     */
    constructor(parentId, postAt) { 
        
        NewJsonRecord.initialize(this, parentId, postAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, parentId, postAt) { 
        obj['parentId'] = parentId || '00000000-0000-0000-0000-000000000000';
        obj['postAt'] = postAt;
    }

    /**
     * Constructs a <code>NewJsonRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/NewJsonRecord} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/NewJsonRecord} The populated <code>NewJsonRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewJsonRecord();

            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], 'Number');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], {'String': 'String'});
            }
            if (data.hasOwnProperty('postAt')) {
                obj['postAt'] = ApiClient.convertToType(data['postAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewJsonRecord</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewJsonRecord</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NewJsonRecord.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

NewJsonRecord.RequiredProperties = ["parentId", "postAt"];

/**
 * @member {Boolean} visible
 */
NewJsonRecord.prototype['visible'] = undefined;

/**
 * @member {Number} flags
 */
NewJsonRecord.prototype['flags'] = undefined;

/**
 * @member {String} parentId
 * @default '00000000-0000-0000-0000-000000000000'
 */
NewJsonRecord.prototype['parentId'] = '00000000-0000-0000-0000-000000000000';

/**
 * @member {String} title
 */
NewJsonRecord.prototype['title'] = undefined;

/**
 * @member {Object.<String, String>} values
 */
NewJsonRecord.prototype['values'] = undefined;

/**
 * @member {Date} postAt
 */
NewJsonRecord.prototype['postAt'] = undefined;






export default NewJsonRecord;

