/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Link from './Link';
import PageMetadata from './PageMetadata';
import PagedModelEntityModelResourceRecordViewEmbedded from './PagedModelEntityModelResourceRecordViewEmbedded';

/**
 * The PagedModelEntityModelResourceRecordView model module.
 * @module su.svn.lib.core.model/PagedModelEntityModelResourceRecordView
 * @version v0
 */
class PagedModelEntityModelResourceRecordView {
    /**
     * Constructs a new <code>PagedModelEntityModelResourceRecordView</code>.
     * @alias module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView
     */
    constructor() { 
        
        PagedModelEntityModelResourceRecordView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PagedModelEntityModelResourceRecordView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView} The populated <code>PagedModelEntityModelResourceRecordView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedModelEntityModelResourceRecordView();

            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = PagedModelEntityModelResourceRecordViewEmbedded.constructFromObject(data['_embedded']);
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': Link});
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = PageMetadata.constructFromObject(data['page']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagedModelEntityModelResourceRecordView</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagedModelEntityModelResourceRecordView</code>.
     */
    static validateJSON(data) {
        // validate the optional field `_embedded`
        if (data['_embedded']) { // data not null
          PagedModelEntityModelResourceRecordViewEmbedded.validateJSON(data['_embedded']);
        }
        // validate the optional field `page`
        if (data['page']) { // data not null
          PageMetadata.validateJSON(data['page']);
        }

        return true;
    }


}



/**
 * @member {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded} _embedded
 */
PagedModelEntityModelResourceRecordView.prototype['_embedded'] = undefined;

/**
 * @member {Object.<String, module:su.svn.lib.core.model/Link>} _links
 */
PagedModelEntityModelResourceRecordView.prototype['_links'] = undefined;

/**
 * @member {module:su.svn.lib.core.model/PageMetadata} page
 */
PagedModelEntityModelResourceRecordView.prototype['page'] = undefined;






export default PagedModelEntityModelResourceRecordView;

