/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Pageable model module.
 * @module su.svn.lib.core.model/Pageable
 * @version v0
 */
class Pageable {
    /**
     * Constructs a new <code>Pageable</code>.
     * @alias module:su.svn.lib.core.model/Pageable
     */
    constructor() { 
        
        Pageable.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Pageable</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/Pageable} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/Pageable} The populated <code>Pageable</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Pageable();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('sort')) {
                obj['sort'] = ApiClient.convertToType(data['sort'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Pageable</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Pageable</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['sort'])) {
            throw new Error("Expected the field `sort` to be an array in the JSON data but got " + data['sort']);
        }

        return true;
    }


}



/**
 * @member {Number} page
 */
Pageable.prototype['page'] = undefined;

/**
 * @member {Number} size
 */
Pageable.prototype['size'] = undefined;

/**
 * @member {Array.<String>} sort
 */
Pageable.prototype['sort'] = undefined;






export default Pageable;

