/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageMetadata model module.
 * @module su.svn.lib.core.model/PageMetadata
 * @version v0
 */
class PageMetadata {
    /**
     * Constructs a new <code>PageMetadata</code>.
     * @alias module:su.svn.lib.core.model/PageMetadata
     */
    constructor() { 
        
        PageMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/PageMetadata} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/PageMetadata} The populated <code>PageMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageMetadata();

            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageMetadata</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} size
 */
PageMetadata.prototype['size'] = undefined;

/**
 * @member {Number} totalElements
 */
PageMetadata.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
PageMetadata.prototype['totalPages'] = undefined;

/**
 * @member {Number} number
 */
PageMetadata.prototype['number'] = undefined;






export default PageMetadata;

