/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityModelResourceRecordView from './EntityModelResourceRecordView';

/**
 * The PagedModelEntityModelResourceRecordViewEmbedded model module.
 * @module su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded
 * @version v0
 */
class PagedModelEntityModelResourceRecordViewEmbedded {
    /**
     * Constructs a new <code>PagedModelEntityModelResourceRecordViewEmbedded</code>.
     * @alias module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded
     */
    constructor() { 
        
        PagedModelEntityModelResourceRecordViewEmbedded.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PagedModelEntityModelResourceRecordViewEmbedded</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded} The populated <code>PagedModelEntityModelResourceRecordViewEmbedded</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedModelEntityModelResourceRecordViewEmbedded();

            if (data.hasOwnProperty('resourceRecordViewList')) {
                obj['resourceRecordViewList'] = ApiClient.convertToType(data['resourceRecordViewList'], [EntityModelResourceRecordView]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagedModelEntityModelResourceRecordViewEmbedded</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagedModelEntityModelResourceRecordViewEmbedded</code>.
     */
    static validateJSON(data) {
        if (data['resourceRecordViewList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['resourceRecordViewList'])) {
                throw new Error("Expected the field `resourceRecordViewList` to be an array in the JSON data but got " + data['resourceRecordViewList']);
            }
            // validate the optional field `resourceRecordViewList` (array)
            for (const item of data['resourceRecordViewList']) {
                EntityModelResourceRecordView.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:su.svn.lib.core.model/EntityModelResourceRecordView>} resourceRecordViewList
 */
PagedModelEntityModelResourceRecordViewEmbedded.prototype['resourceRecordViewList'] = undefined;






export default PagedModelEntityModelResourceRecordViewEmbedded;

