/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResourceRecordViewFilter model module.
 * @module su.svn.lib.core.model/ResourceRecordViewFilter
 * @version v0
 */
class ResourceRecordViewFilter {
    /**
     * Constructs a new <code>ResourceRecordViewFilter</code>.
     * @alias module:su.svn.lib.core.model/ResourceRecordViewFilter
     */
    constructor() { 
        
        ResourceRecordViewFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResourceRecordViewFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/ResourceRecordViewFilter} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/ResourceRecordViewFilter} The populated <code>ResourceRecordViewFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceRecordViewFilter();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('fromTime')) {
                obj['fromTime'] = ApiClient.convertToType(data['fromTime'], 'Date');
            }
            if (data.hasOwnProperty('fromDate')) {
                obj['fromDate'] = ApiClient.convertToType(data['fromDate'], 'Date');
            }
            if (data.hasOwnProperty('toDate')) {
                obj['toDate'] = ApiClient.convertToType(data['toDate'], 'Date');
            }
            if (data.hasOwnProperty('withDisabled')) {
                obj['withDisabled'] = ApiClient.convertToType(data['withDisabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceRecordViewFilter</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceRecordViewFilter</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
ResourceRecordViewFilter.prototype['title'] = undefined;

/**
 * @member {Date} fromTime
 */
ResourceRecordViewFilter.prototype['fromTime'] = undefined;

/**
 * @member {Date} fromDate
 */
ResourceRecordViewFilter.prototype['fromDate'] = undefined;

/**
 * @member {Date} toDate
 */
ResourceRecordViewFilter.prototype['toDate'] = undefined;

/**
 * @member {Boolean} withDisabled
 */
ResourceRecordViewFilter.prototype['withDisabled'] = undefined;






export default ResourceRecordViewFilter;

