/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResourceJsonRecord model module.
 * @module su.svn.lib.core.model/ResourceJsonRecord
 * @version v0
 */
class ResourceJsonRecord {
    /**
     * Constructs a new <code>ResourceJsonRecord</code>.
     * @alias module:su.svn.lib.core.model/ResourceJsonRecord
     */
    constructor() { 
        
        ResourceJsonRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResourceJsonRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:su.svn.lib.core.model/ResourceJsonRecord} obj Optional instance to populate.
     * @return {module:su.svn.lib.core.model/ResourceJsonRecord} The populated <code>ResourceJsonRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResourceJsonRecord();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = ApiClient.convertToType(data['flags'], 'Number');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], {'String': 'String'});
            }
            if (data.hasOwnProperty('postAt')) {
                obj['postAt'] = ApiClient.convertToType(data['postAt'], 'Date');
            }
            if (data.hasOwnProperty('refreshAt')) {
                obj['refreshAt'] = ApiClient.convertToType(data['refreshAt'], 'Date');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResourceJsonRecord</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResourceJsonRecord</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['parentId'] && !(typeof data['parentId'] === 'string' || data['parentId'] instanceof String)) {
            throw new Error("Expected the field `parentId` to be a primitive type in the JSON string but got " + data['parentId']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ResourceJsonRecord.prototype['id'] = undefined;

/**
 * @member {Boolean} visible
 */
ResourceJsonRecord.prototype['visible'] = undefined;

/**
 * @member {Number} flags
 */
ResourceJsonRecord.prototype['flags'] = undefined;

/**
 * @member {String} parentId
 */
ResourceJsonRecord.prototype['parentId'] = undefined;

/**
 * @member {String} title
 */
ResourceJsonRecord.prototype['title'] = undefined;

/**
 * @member {Object.<String, String>} json
 */
ResourceJsonRecord.prototype['json'] = undefined;

/**
 * @member {Date} postAt
 */
ResourceJsonRecord.prototype['postAt'] = undefined;

/**
 * @member {Date} refreshAt
 */
ResourceJsonRecord.prototype['refreshAt'] = undefined;

/**
 * @member {Array.<String>} tags
 */
ResourceJsonRecord.prototype['tags'] = undefined;






export default ResourceJsonRecord;

