/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HelloControllerApi
 */
@Disabled
public class HelloControllerApiTest {

    private final HelloControllerApi api = new HelloControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void helloTest() throws ApiException {
        String response = api.hello();
        // TODO: test validations
    }

}
