/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.api;

import su.svn.lib.core.ApiException;
import su.svn.lib.core.model.ErrorResponse;
import su.svn.lib.core.model.PageResourceRecordView;
import su.svn.lib.core.model.Pageable;
import su.svn.lib.core.model.ResourceRecordViewFilter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecordViewControllerApi
 */
@Disabled
public class RecordViewControllerApiTest {

    private final RecordViewControllerApi api = new RecordViewControllerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllRecordsTest() throws ApiException {
        ResourceRecordViewFilter filter = null;
        Pageable pageable = null;
        PageResourceRecordView response = api.getAllRecords(filter, pageable);
        // TODO: test validations
    }

}
