/*
 * This file was last modified at 2026.04.15 20:40 by Victor N. Skurikhin.
 * This is free and unencumbered software released into the public domain.
 * For more information, please refer to <http://unlicense.org>
 * AuthApi.java
 * $Id$
 */

/*
 * DayBook Auth API
 * API for authentication in DayBook
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.auth.api;

import su.svn.lib.auth.ApiCallback;
import su.svn.lib.auth.ApiClient;
import su.svn.lib.auth.ApiException;
import su.svn.lib.auth.ApiResponse;
import su.svn.lib.auth.Configuration;
import su.svn.lib.auth.Pair;
import su.svn.lib.auth.ProgressRequestBody;
import su.svn.lib.auth.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import su.svn.lib.auth.model.CreateUser;
import su.svn.lib.auth.model.Login;
import su.svn.lib.auth.model.ModelAPIResponse;
import su.svn.lib.auth.model.V2AuthPost200Response;
import su.svn.lib.auth.model.V2AuthPost400Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuthApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v2AuthPost
     * @param request User credentials (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2AuthPostCall(@javax.annotation.Nonnull Login request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = request;

        // create path and map variables
        String localVarPath = "/v2/auth";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v2AuthPostValidateBeforeCall(@javax.annotation.Nonnull Login request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling v2AuthPost(Async)");
        }

        return v2AuthPostCall(request, _callback);

    }

    /**
     * Authenticate user
     * Authenticates user using login and password. Returns access token and sets refresh token cookie.
     * @param request User credentials (required)
     * @return V2AuthPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public V2AuthPost200Response v2AuthPost(@javax.annotation.Nonnull Login request) throws ApiException {
        ApiResponse<V2AuthPost200Response> localVarResp = v2AuthPostWithHttpInfo(request);
        return localVarResp.getData();
    }

    /**
     * Authenticate user
     * Authenticates user using login and password. Returns access token and sets refresh token cookie.
     * @param request User credentials (required)
     * @return ApiResponse&lt;V2AuthPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<V2AuthPost200Response> v2AuthPostWithHttpInfo(@javax.annotation.Nonnull Login request) throws ApiException {
        okhttp3.Call localVarCall = v2AuthPostValidateBeforeCall(request, null);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Authenticate user (asynchronously)
     * Authenticates user using login and password. Returns access token and sets refresh token cookie.
     * @param request User credentials (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2AuthPostAsync(@javax.annotation.Nonnull Login request, final ApiCallback<V2AuthPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = v2AuthPostValidateBeforeCall(request, _callback);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v2LogoutPost
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2LogoutPostCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/logout";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v2LogoutPostValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return v2LogoutPostCall(_callback);

    }

    /**
     * Logout user
     * Invalidates user session. Requires JWT authentication.
     * @return ModelAPIResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ModelAPIResponse v2LogoutPost() throws ApiException {
        ApiResponse<ModelAPIResponse> localVarResp = v2LogoutPostWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Logout user
     * Invalidates user session. Requires JWT authentication.
     * @return ApiResponse&lt;ModelAPIResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ModelAPIResponse> v2LogoutPostWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = v2LogoutPostValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ModelAPIResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Logout user (asynchronously)
     * Invalidates user session. Requires JWT authentication.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2LogoutPostAsync(final ApiCallback<ModelAPIResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v2LogoutPostValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ModelAPIResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v2RefreshPost
     * @param request User credentials by cookie string (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 206 </td><td> Partial Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2RefreshPostCall(@javax.annotation.Nonnull Login request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = request;

        // create path and map variables
        String localVarPath = "/v2/refresh";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v2RefreshPostValidateBeforeCall(@javax.annotation.Nonnull Login request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling v2RefreshPost(Async)");
        }

        return v2RefreshPostCall(request, _callback);

    }

    /**
     * Refresh tokens
     * Refreshes access token using refresh token from cookie. Sets new refresh cookie.
     * @param request User credentials by cookie string (required)
     * @return V2AuthPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 206 </td><td> Partial Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public V2AuthPost200Response v2RefreshPost(@javax.annotation.Nonnull Login request) throws ApiException {
        ApiResponse<V2AuthPost200Response> localVarResp = v2RefreshPostWithHttpInfo(request);
        return localVarResp.getData();
    }

    /**
     * Refresh tokens
     * Refreshes access token using refresh token from cookie. Sets new refresh cookie.
     * @param request User credentials by cookie string (required)
     * @return ApiResponse&lt;V2AuthPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 206 </td><td> Partial Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<V2AuthPost200Response> v2RefreshPostWithHttpInfo(@javax.annotation.Nonnull Login request) throws ApiException {
        okhttp3.Call localVarCall = v2RefreshPostValidateBeforeCall(request, null);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Refresh tokens (asynchronously)
     * Refreshes access token using refresh token from cookie. Sets new refresh cookie.
     * @param request User credentials by cookie string (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 206 </td><td> Partial Content </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> unauthorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2RefreshPostAsync(@javax.annotation.Nonnull Login request, final ApiCallback<V2AuthPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = v2RefreshPostValidateBeforeCall(request, _callback);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v2RegisterPost
     * @param request User registration data (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> status conflict </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2RegisterPostCall(@javax.annotation.Nonnull CreateUser request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = request;

        // create path and map variables
        String localVarPath = "/v2/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v2RegisterPostValidateBeforeCall(@javax.annotation.Nonnull CreateUser request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling v2RegisterPost(Async)");
        }

        return v2RegisterPostCall(request, _callback);

    }

    /**
     * Register user
     * Registers a new user and returns access token with refresh cookie.
     * @param request User registration data (required)
     * @return V2AuthPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> status conflict </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public V2AuthPost200Response v2RegisterPost(@javax.annotation.Nonnull CreateUser request) throws ApiException {
        ApiResponse<V2AuthPost200Response> localVarResp = v2RegisterPostWithHttpInfo(request);
        return localVarResp.getData();
    }

    /**
     * Register user
     * Registers a new user and returns access token with refresh cookie.
     * @param request User registration data (required)
     * @return ApiResponse&lt;V2AuthPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> status conflict </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<V2AuthPost200Response> v2RegisterPostWithHttpInfo(@javax.annotation.Nonnull CreateUser request) throws ApiException {
        okhttp3.Call localVarCall = v2RegisterPostValidateBeforeCall(request, null);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register user (asynchronously)
     * Registers a new user and returns access token with refresh cookie.
     * @param request User registration data (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> bad request </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> status conflict </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> server error &#39;success&#39;: false </td><td>  -  </td></tr>
        <tr><td> 503 </td><td> service unavailable </td><td>  -  </td></tr>
        <tr><td> 504 </td><td> gateway timeout </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v2RegisterPostAsync(@javax.annotation.Nonnull CreateUser request, final ApiCallback<V2AuthPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = v2RegisterPostValidateBeforeCall(request, _callback);
        Type localVarReturnType = new TypeToken<V2AuthPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
