// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/handler (interfaces: ApiHandlers)
//
// Generated by this command:
//
//	mockgen -destination=api_handlers_mock_test.go -package=handler github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/handler ApiHandlers
//

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	chi "github.com/go-chi/chi/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockApiHandlers is a mock of ApiHandlers interface.
type MockApiHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockApiHandlersMockRecorder
	isgomock struct{}
}

// MockApiHandlersMockRecorder is the mock recorder for MockApiHandlers.
type MockApiHandlersMockRecorder struct {
	mock *MockApiHandlers
}

// NewMockApiHandlers creates a new mock instance.
func NewMockApiHandlers(ctrl *gomock.Controller) *MockApiHandlers {
	mock := &MockApiHandlers{ctrl: ctrl}
	mock.recorder = &MockApiHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiHandlers) EXPECT() *MockApiHandlersMockRecorder {
	return m.recorder
}

// apiV1 mocks base method.
func (m *MockApiHandlers) apiV1() chi.Router {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "apiV1")
	ret0, _ := ret[0].(chi.Router)
	return ret0
}

// apiV1 indicates an expected call of apiV1.
func (mr *MockApiHandlersMockRecorder) apiV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "apiV1", reflect.TypeOf((*MockApiHandlers)(nil).apiV1))
}

// apiV2 mocks base method.
func (m *MockApiHandlers) apiV2() chi.Router {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "apiV2")
	ret0, _ := ret[0].(chi.Router)
	return ret0
}

// apiV2 indicates an expected call of apiV2.
func (mr *MockApiHandlersMockRecorder) apiV2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "apiV2", reflect.TypeOf((*MockApiHandlers)(nil).apiV2))
}
