=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PagedModelEntityModelResourceRecordView
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PagedModelEntityModelResourceRecordView do
  #let(:instance) { OpenapiClient::PagedModelEntityModelResourceRecordView.new }

  describe 'test an instance of PagedModelEntityModelResourceRecordView' do
    it 'should create an instance of PagedModelEntityModelResourceRecordView' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PagedModelEntityModelResourceRecordView)
    end
  end

  describe 'test attribute "_embedded"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_links"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "page"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
