=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PageMetadata
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PageMetadata do
  #let(:instance) { OpenapiClient::PageMetadata.new }

  describe 'test an instance of PageMetadata' do
    it 'should create an instance of PageMetadata' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PageMetadata)
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total_elements"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total_pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
