quarkus.openapi.generator.spec=openapi.yml
quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa
quarkus.hibernate-orm.blocking=false
quarkus.hibernate-orm.mapping.format.global=ignore
quarkus.jackson.write-dates-as-timestamps=false
quarkus.hibernate-orm.fetch.batch-size=1024
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dbuser
quarkus.datasource.password=password
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/db?application_name=api&currentSchema=api&loggerLevel=TRACE
quarkus.datasource.reactive.max-size=20
quarkus.rest-client."su.svn.api.repository.client.rest.JsonRecordClient".url=http://localhost:8081
quarkus.rest-client."su.svn.api.repository.client.rest.RecordViewClient".url=http://localhost:8081
# Enable JWT RBAC
#quarkus.smallrye-jwt.enabled=true
# Set the verification algorithm to HS256
#smallrye.jwt.verify.secretkey=RmRoOXU4cklOeGZpdmJyaWFuYmJWVDF1MjMyVlFCWllLeDFIR0FHUHQySQ==
#smallrye.jwt.verify.algorithm=HS256
#smallrye.jwt.verify.key-format=JWK_BASE64URL
#mp.jwt.verify.publickey.algorithm=HS256
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".level=TRACE
#quarkus.log.category."io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator".min-level=TRACE
mp.jwt.verify.issuer=cd8f5f9f-e3e8-569f-87ef-f03c6cfc29bc
smallrye.jwt.time-to-live=-1
#smallrye.jwt.verify.key-format=JWK
#smallrye.jwt.verify.key.location=jwt_hs256_sign_key.jwk
