// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/config"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/env"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/handler"
)

// Injectors from di.go:

func InitializeServer(cfg config.Config, environments env.Environments) *server.AuthServer {
	httpHandler := handler.NewRouter(cfg, environments)
	authServer := server.NewAuthServer(cfg, environments, httpHandler)
	return authServer
}

// di.go:

var (
	serverSet = wire.NewSet(config.GetConfig, env.EnvironmentsLoad, server.NewAuthServer, handler.NewRouter)
)
