// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server"
	"github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/config"
)

// Injectors from di.go:

func InitializeServer(cfg config.Config) *server.AuthServer {
	authServer := server.NewAuthServer(cfg)
	return authServer
}

// di.go:

var (
	serverSet = wire.NewSet(config.GetConfig, server.NewAuthServer)
)
