/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
)

// checks if the PagedModelEntityModelResourceRecordViewEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagedModelEntityModelResourceRecordViewEmbedded{}

// PagedModelEntityModelResourceRecordViewEmbedded struct for PagedModelEntityModelResourceRecordViewEmbedded
type PagedModelEntityModelResourceRecordViewEmbedded struct {
	ResourceRecordViewList []EntityModelResourceRecordView `json:"resourceRecordViewList,omitempty"`
}

// NewPagedModelEntityModelResourceRecordViewEmbedded instantiates a new PagedModelEntityModelResourceRecordViewEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagedModelEntityModelResourceRecordViewEmbedded() *PagedModelEntityModelResourceRecordViewEmbedded {
	this := PagedModelEntityModelResourceRecordViewEmbedded{}
	return &this
}

// NewPagedModelEntityModelResourceRecordViewEmbeddedWithDefaults instantiates a new PagedModelEntityModelResourceRecordViewEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagedModelEntityModelResourceRecordViewEmbeddedWithDefaults() *PagedModelEntityModelResourceRecordViewEmbedded {
	this := PagedModelEntityModelResourceRecordViewEmbedded{}
	return &this
}

// GetResourceRecordViewList returns the ResourceRecordViewList field value if set, zero value otherwise.
func (o *PagedModelEntityModelResourceRecordViewEmbedded) GetResourceRecordViewList() []EntityModelResourceRecordView {
	if o == nil || IsNil(o.ResourceRecordViewList) {
		var ret []EntityModelResourceRecordView
		return ret
	}
	return o.ResourceRecordViewList
}

// GetResourceRecordViewListOk returns a tuple with the ResourceRecordViewList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedModelEntityModelResourceRecordViewEmbedded) GetResourceRecordViewListOk() ([]EntityModelResourceRecordView, bool) {
	if o == nil || IsNil(o.ResourceRecordViewList) {
		return nil, false
	}
	return o.ResourceRecordViewList, true
}

// HasResourceRecordViewList returns a boolean if a field has been set.
func (o *PagedModelEntityModelResourceRecordViewEmbedded) HasResourceRecordViewList() bool {
	if o != nil && !IsNil(o.ResourceRecordViewList) {
		return true
	}

	return false
}

// SetResourceRecordViewList gets a reference to the given []EntityModelResourceRecordView and assigns it to the ResourceRecordViewList field.
func (o *PagedModelEntityModelResourceRecordViewEmbedded) SetResourceRecordViewList(v []EntityModelResourceRecordView) {
	o.ResourceRecordViewList = v
}

func (o PagedModelEntityModelResourceRecordViewEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagedModelEntityModelResourceRecordViewEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ResourceRecordViewList) {
		toSerialize["resourceRecordViewList"] = o.ResourceRecordViewList
	}
	return toSerialize, nil
}

type NullablePagedModelEntityModelResourceRecordViewEmbedded struct {
	value *PagedModelEntityModelResourceRecordViewEmbedded
	isSet bool
}

func (v NullablePagedModelEntityModelResourceRecordViewEmbedded) Get() *PagedModelEntityModelResourceRecordViewEmbedded {
	return v.value
}

func (v *NullablePagedModelEntityModelResourceRecordViewEmbedded) Set(val *PagedModelEntityModelResourceRecordViewEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullablePagedModelEntityModelResourceRecordViewEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullablePagedModelEntityModelResourceRecordViewEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagedModelEntityModelResourceRecordViewEmbedded(val *PagedModelEntityModelResourceRecordViewEmbedded) *NullablePagedModelEntityModelResourceRecordViewEmbedded {
	return &NullablePagedModelEntityModelResourceRecordViewEmbedded{value: val, isSet: true}
}

func (v NullablePagedModelEntityModelResourceRecordViewEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagedModelEntityModelResourceRecordViewEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


