/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
)

// checks if the PagedModelEntityModelResourceRecordView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PagedModelEntityModelResourceRecordView{}

// PagedModelEntityModelResourceRecordView struct for PagedModelEntityModelResourceRecordView
type PagedModelEntityModelResourceRecordView struct {
	Embedded *PagedModelEntityModelResourceRecordViewEmbedded `json:"_embedded,omitempty"`
	Links map[string]Link `json:"_links,omitempty"`
	Page *PageMetadata `json:"page,omitempty"`
}

// NewPagedModelEntityModelResourceRecordView instantiates a new PagedModelEntityModelResourceRecordView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPagedModelEntityModelResourceRecordView() *PagedModelEntityModelResourceRecordView {
	this := PagedModelEntityModelResourceRecordView{}
	return &this
}

// NewPagedModelEntityModelResourceRecordViewWithDefaults instantiates a new PagedModelEntityModelResourceRecordView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPagedModelEntityModelResourceRecordViewWithDefaults() *PagedModelEntityModelResourceRecordView {
	this := PagedModelEntityModelResourceRecordView{}
	return &this
}

// GetEmbedded returns the Embedded field value if set, zero value otherwise.
func (o *PagedModelEntityModelResourceRecordView) GetEmbedded() PagedModelEntityModelResourceRecordViewEmbedded {
	if o == nil || IsNil(o.Embedded) {
		var ret PagedModelEntityModelResourceRecordViewEmbedded
		return ret
	}
	return *o.Embedded
}

// GetEmbeddedOk returns a tuple with the Embedded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedModelEntityModelResourceRecordView) GetEmbeddedOk() (*PagedModelEntityModelResourceRecordViewEmbedded, bool) {
	if o == nil || IsNil(o.Embedded) {
		return nil, false
	}
	return o.Embedded, true
}

// HasEmbedded returns a boolean if a field has been set.
func (o *PagedModelEntityModelResourceRecordView) HasEmbedded() bool {
	if o != nil && !IsNil(o.Embedded) {
		return true
	}

	return false
}

// SetEmbedded gets a reference to the given PagedModelEntityModelResourceRecordViewEmbedded and assigns it to the Embedded field.
func (o *PagedModelEntityModelResourceRecordView) SetEmbedded(v PagedModelEntityModelResourceRecordViewEmbedded) {
	o.Embedded = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *PagedModelEntityModelResourceRecordView) GetLinks() map[string]Link {
	if o == nil || IsNil(o.Links) {
		var ret map[string]Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedModelEntityModelResourceRecordView) GetLinksOk() (map[string]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return map[string]Link{}, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *PagedModelEntityModelResourceRecordView) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]Link and assigns it to the Links field.
func (o *PagedModelEntityModelResourceRecordView) SetLinks(v map[string]Link) {
	o.Links = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PagedModelEntityModelResourceRecordView) GetPage() PageMetadata {
	if o == nil || IsNil(o.Page) {
		var ret PageMetadata
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PagedModelEntityModelResourceRecordView) GetPageOk() (*PageMetadata, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PagedModelEntityModelResourceRecordView) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given PageMetadata and assigns it to the Page field.
func (o *PagedModelEntityModelResourceRecordView) SetPage(v PageMetadata) {
	o.Page = &v
}

func (o PagedModelEntityModelResourceRecordView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PagedModelEntityModelResourceRecordView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Embedded) {
		toSerialize["_embedded"] = o.Embedded
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullablePagedModelEntityModelResourceRecordView struct {
	value *PagedModelEntityModelResourceRecordView
	isSet bool
}

func (v NullablePagedModelEntityModelResourceRecordView) Get() *PagedModelEntityModelResourceRecordView {
	return v.value
}

func (v *NullablePagedModelEntityModelResourceRecordView) Set(val *PagedModelEntityModelResourceRecordView) {
	v.value = val
	v.isSet = true
}

func (v NullablePagedModelEntityModelResourceRecordView) IsSet() bool {
	return v.isSet
}

func (v *NullablePagedModelEntityModelResourceRecordView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePagedModelEntityModelResourceRecordView(val *PagedModelEntityModelResourceRecordView) *NullablePagedModelEntityModelResourceRecordView {
	return &NullablePagedModelEntityModelResourceRecordView{value: val, isSet: true}
}

func (v NullablePagedModelEntityModelResourceRecordView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePagedModelEntityModelResourceRecordView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


