/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
)

// checks if the EntityModelResourceRecordView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityModelResourceRecordView{}

// EntityModelResourceRecordView struct for EntityModelResourceRecordView
type EntityModelResourceRecordView struct {
	Id *string `json:"id,omitempty"`
	Visible *bool `json:"visible,omitempty"`
	Flags *int32 `json:"flags,omitempty"`
	ParentId *string `json:"parentId,omitempty"`
	UserName *string `json:"userName,omitempty"`
	PostAt *time.Time `json:"postAt,omitempty"`
	RefreshAt *time.Time `json:"refreshAt,omitempty"`
	LastChangedTime *time.Time `json:"lastChangedTime,omitempty"`
	Title *string `json:"title,omitempty"`
	Json map[string]string `json:"json,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Links map[string]Link `json:"_links,omitempty"`
}

// NewEntityModelResourceRecordView instantiates a new EntityModelResourceRecordView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityModelResourceRecordView() *EntityModelResourceRecordView {
	this := EntityModelResourceRecordView{}
	return &this
}

// NewEntityModelResourceRecordViewWithDefaults instantiates a new EntityModelResourceRecordView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityModelResourceRecordViewWithDefaults() *EntityModelResourceRecordView {
	this := EntityModelResourceRecordView{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EntityModelResourceRecordView) SetId(v string) {
	o.Id = &v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetVisible() bool {
	if o == nil || IsNil(o.Visible) {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *EntityModelResourceRecordView) SetVisible(v bool) {
	o.Visible = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *EntityModelResourceRecordView) SetFlags(v int32) {
	o.Flags = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *EntityModelResourceRecordView) SetParentId(v string) {
	o.ParentId = &v
}

// GetUserName returns the UserName field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetUserName() string {
	if o == nil || IsNil(o.UserName) {
		var ret string
		return ret
	}
	return *o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.UserName) {
		return nil, false
	}
	return o.UserName, true
}

// HasUserName returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasUserName() bool {
	if o != nil && !IsNil(o.UserName) {
		return true
	}

	return false
}

// SetUserName gets a reference to the given string and assigns it to the UserName field.
func (o *EntityModelResourceRecordView) SetUserName(v string) {
	o.UserName = &v
}

// GetPostAt returns the PostAt field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetPostAt() time.Time {
	if o == nil || IsNil(o.PostAt) {
		var ret time.Time
		return ret
	}
	return *o.PostAt
}

// GetPostAtOk returns a tuple with the PostAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetPostAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PostAt) {
		return nil, false
	}
	return o.PostAt, true
}

// HasPostAt returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasPostAt() bool {
	if o != nil && !IsNil(o.PostAt) {
		return true
	}

	return false
}

// SetPostAt gets a reference to the given time.Time and assigns it to the PostAt field.
func (o *EntityModelResourceRecordView) SetPostAt(v time.Time) {
	o.PostAt = &v
}

// GetRefreshAt returns the RefreshAt field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetRefreshAt() time.Time {
	if o == nil || IsNil(o.RefreshAt) {
		var ret time.Time
		return ret
	}
	return *o.RefreshAt
}

// GetRefreshAtOk returns a tuple with the RefreshAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetRefreshAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RefreshAt) {
		return nil, false
	}
	return o.RefreshAt, true
}

// HasRefreshAt returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasRefreshAt() bool {
	if o != nil && !IsNil(o.RefreshAt) {
		return true
	}

	return false
}

// SetRefreshAt gets a reference to the given time.Time and assigns it to the RefreshAt field.
func (o *EntityModelResourceRecordView) SetRefreshAt(v time.Time) {
	o.RefreshAt = &v
}

// GetLastChangedTime returns the LastChangedTime field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetLastChangedTime() time.Time {
	if o == nil || IsNil(o.LastChangedTime) {
		var ret time.Time
		return ret
	}
	return *o.LastChangedTime
}

// GetLastChangedTimeOk returns a tuple with the LastChangedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetLastChangedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastChangedTime) {
		return nil, false
	}
	return o.LastChangedTime, true
}

// HasLastChangedTime returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasLastChangedTime() bool {
	if o != nil && !IsNil(o.LastChangedTime) {
		return true
	}

	return false
}

// SetLastChangedTime gets a reference to the given time.Time and assigns it to the LastChangedTime field.
func (o *EntityModelResourceRecordView) SetLastChangedTime(v time.Time) {
	o.LastChangedTime = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *EntityModelResourceRecordView) SetTitle(v string) {
	o.Title = &v
}

// GetJson returns the Json field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetJson() map[string]string {
	if o == nil || IsNil(o.Json) {
		var ret map[string]string
		return ret
	}
	return o.Json
}

// GetJsonOk returns a tuple with the Json field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetJsonOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Json) {
		return map[string]string{}, false
	}
	return o.Json, true
}

// HasJson returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasJson() bool {
	if o != nil && !IsNil(o.Json) {
		return true
	}

	return false
}

// SetJson gets a reference to the given map[string]string and assigns it to the Json field.
func (o *EntityModelResourceRecordView) SetJson(v map[string]string) {
	o.Json = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *EntityModelResourceRecordView) SetTags(v []string) {
	o.Tags = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *EntityModelResourceRecordView) GetLinks() map[string]Link {
	if o == nil || IsNil(o.Links) {
		var ret map[string]Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityModelResourceRecordView) GetLinksOk() (map[string]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return map[string]Link{}, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *EntityModelResourceRecordView) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given map[string]Link and assigns it to the Links field.
func (o *EntityModelResourceRecordView) SetLinks(v map[string]Link) {
	o.Links = v
}

func (o EntityModelResourceRecordView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityModelResourceRecordView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	if !IsNil(o.UserName) {
		toSerialize["userName"] = o.UserName
	}
	if !IsNil(o.PostAt) {
		toSerialize["postAt"] = o.PostAt
	}
	if !IsNil(o.RefreshAt) {
		toSerialize["refreshAt"] = o.RefreshAt
	}
	if !IsNil(o.LastChangedTime) {
		toSerialize["lastChangedTime"] = o.LastChangedTime
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Json) {
		toSerialize["json"] = o.Json
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableEntityModelResourceRecordView struct {
	value *EntityModelResourceRecordView
	isSet bool
}

func (v NullableEntityModelResourceRecordView) Get() *EntityModelResourceRecordView {
	return v.value
}

func (v *NullableEntityModelResourceRecordView) Set(val *EntityModelResourceRecordView) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityModelResourceRecordView) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityModelResourceRecordView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityModelResourceRecordView(val *EntityModelResourceRecordView) *NullableEntityModelResourceRecordView {
	return &NullableEntityModelResourceRecordView{value: val, isSet: true}
}

func (v NullableEntityModelResourceRecordView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityModelResourceRecordView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


