/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
)

// checks if the ResourceJsonRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceJsonRecord{}

// ResourceJsonRecord struct for ResourceJsonRecord
type ResourceJsonRecord struct {
	Id *string `json:"id,omitempty"`
	Visible *bool `json:"visible,omitempty"`
	Flags *int32 `json:"flags,omitempty"`
	ParentId *string `json:"parentId,omitempty"`
	Title *string `json:"title,omitempty"`
	Values map[string]string `json:"values,omitempty"`
	PostAt *time.Time `json:"postAt,omitempty"`
	RefreshAt *time.Time `json:"refreshAt,omitempty"`
}

// NewResourceJsonRecord instantiates a new ResourceJsonRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceJsonRecord() *ResourceJsonRecord {
	this := ResourceJsonRecord{}
	return &this
}

// NewResourceJsonRecordWithDefaults instantiates a new ResourceJsonRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceJsonRecordWithDefaults() *ResourceJsonRecord {
	this := ResourceJsonRecord{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ResourceJsonRecord) SetId(v string) {
	o.Id = &v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetVisible() bool {
	if o == nil || IsNil(o.Visible) {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *ResourceJsonRecord) SetVisible(v bool) {
	o.Visible = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *ResourceJsonRecord) SetFlags(v int32) {
	o.Flags = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *ResourceJsonRecord) SetParentId(v string) {
	o.ParentId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ResourceJsonRecord) SetTitle(v string) {
	o.Title = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetValues() map[string]string {
	if o == nil || IsNil(o.Values) {
		var ret map[string]string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetValuesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]string{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]string and assigns it to the Values field.
func (o *ResourceJsonRecord) SetValues(v map[string]string) {
	o.Values = v
}

// GetPostAt returns the PostAt field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetPostAt() time.Time {
	if o == nil || IsNil(o.PostAt) {
		var ret time.Time
		return ret
	}
	return *o.PostAt
}

// GetPostAtOk returns a tuple with the PostAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetPostAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PostAt) {
		return nil, false
	}
	return o.PostAt, true
}

// HasPostAt returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasPostAt() bool {
	if o != nil && !IsNil(o.PostAt) {
		return true
	}

	return false
}

// SetPostAt gets a reference to the given time.Time and assigns it to the PostAt field.
func (o *ResourceJsonRecord) SetPostAt(v time.Time) {
	o.PostAt = &v
}

// GetRefreshAt returns the RefreshAt field value if set, zero value otherwise.
func (o *ResourceJsonRecord) GetRefreshAt() time.Time {
	if o == nil || IsNil(o.RefreshAt) {
		var ret time.Time
		return ret
	}
	return *o.RefreshAt
}

// GetRefreshAtOk returns a tuple with the RefreshAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceJsonRecord) GetRefreshAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RefreshAt) {
		return nil, false
	}
	return o.RefreshAt, true
}

// HasRefreshAt returns a boolean if a field has been set.
func (o *ResourceJsonRecord) HasRefreshAt() bool {
	if o != nil && !IsNil(o.RefreshAt) {
		return true
	}

	return false
}

// SetRefreshAt gets a reference to the given time.Time and assigns it to the RefreshAt field.
func (o *ResourceJsonRecord) SetRefreshAt(v time.Time) {
	o.RefreshAt = &v
}

func (o ResourceJsonRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceJsonRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.PostAt) {
		toSerialize["postAt"] = o.PostAt
	}
	if !IsNil(o.RefreshAt) {
		toSerialize["refreshAt"] = o.RefreshAt
	}
	return toSerialize, nil
}

type NullableResourceJsonRecord struct {
	value *ResourceJsonRecord
	isSet bool
}

func (v NullableResourceJsonRecord) Get() *ResourceJsonRecord {
	return v.value
}

func (v *NullableResourceJsonRecord) Set(val *ResourceJsonRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceJsonRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceJsonRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceJsonRecord(val *ResourceJsonRecord) *NullableResourceJsonRecord {
	return &NullableResourceJsonRecord{value: val, isSet: true}
}

func (v NullableResourceJsonRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceJsonRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


