/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NewJsonRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewJsonRecord{}

// NewJsonRecord struct for NewJsonRecord
type NewJsonRecord struct {
	Visible *bool `json:"visible,omitempty"`
	Flags *int32 `json:"flags,omitempty"`
	ParentId string `json:"parentId"`
	Title *string `json:"title,omitempty"`
	Json map[string]string `json:"json,omitempty"`
	PostAt time.Time `json:"postAt"`
	Tags []string `json:"tags,omitempty"`
}

type _NewJsonRecord NewJsonRecord

// NewNewJsonRecord instantiates a new NewJsonRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewJsonRecord(parentId string, postAt time.Time) *NewJsonRecord {
	this := NewJsonRecord{}
	this.ParentId = parentId
	this.PostAt = postAt
	return &this
}

// NewNewJsonRecordWithDefaults instantiates a new NewJsonRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewJsonRecordWithDefaults() *NewJsonRecord {
	this := NewJsonRecord{}
	var parentId string = "00000000-0000-0000-0000-000000000000"
	this.ParentId = parentId
	return &this
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *NewJsonRecord) GetVisible() bool {
	if o == nil || IsNil(o.Visible) {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *NewJsonRecord) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *NewJsonRecord) SetVisible(v bool) {
	o.Visible = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *NewJsonRecord) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *NewJsonRecord) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *NewJsonRecord) SetFlags(v int32) {
	o.Flags = &v
}

// GetParentId returns the ParentId field value
func (o *NewJsonRecord) GetParentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *NewJsonRecord) SetParentId(v string) {
	o.ParentId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *NewJsonRecord) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *NewJsonRecord) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *NewJsonRecord) SetTitle(v string) {
	o.Title = &v
}

// GetJson returns the Json field value if set, zero value otherwise.
func (o *NewJsonRecord) GetJson() map[string]string {
	if o == nil || IsNil(o.Json) {
		var ret map[string]string
		return ret
	}
	return o.Json
}

// GetJsonOk returns a tuple with the Json field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetJsonOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Json) {
		return map[string]string{}, false
	}
	return o.Json, true
}

// HasJson returns a boolean if a field has been set.
func (o *NewJsonRecord) HasJson() bool {
	if o != nil && !IsNil(o.Json) {
		return true
	}

	return false
}

// SetJson gets a reference to the given map[string]string and assigns it to the Json field.
func (o *NewJsonRecord) SetJson(v map[string]string) {
	o.Json = v
}

// GetPostAt returns the PostAt field value
func (o *NewJsonRecord) GetPostAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PostAt
}

// GetPostAtOk returns a tuple with the PostAt field value
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetPostAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostAt, true
}

// SetPostAt sets field value
func (o *NewJsonRecord) SetPostAt(v time.Time) {
	o.PostAt = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *NewJsonRecord) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewJsonRecord) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *NewJsonRecord) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *NewJsonRecord) SetTags(v []string) {
	o.Tags = v
}

func (o NewJsonRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewJsonRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	toSerialize["parentId"] = o.ParentId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Json) {
		toSerialize["json"] = o.Json
	}
	toSerialize["postAt"] = o.PostAt
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *NewJsonRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parentId",
		"postAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewJsonRecord := _NewJsonRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewJsonRecord)

	if err != nil {
		return err
	}

	*o = NewJsonRecord(varNewJsonRecord)

	return err
}

type NullableNewJsonRecord struct {
	value *NewJsonRecord
	isSet bool
}

func (v NullableNewJsonRecord) Get() *NewJsonRecord {
	return v.value
}

func (v *NullableNewJsonRecord) Set(val *NewJsonRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableNewJsonRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableNewJsonRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewJsonRecord(val *NewJsonRecord) *NullableNewJsonRecord {
	return &NullableNewJsonRecord{value: val, isSet: true}
}

func (v NullableNewJsonRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewJsonRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


