/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UpdateJsonRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateJsonRecord{}

// UpdateJsonRecord struct for UpdateJsonRecord
type UpdateJsonRecord struct {
	Id string `json:"id"`
	ParentId string `json:"parentId"`
	Title *string `json:"title,omitempty"`
	Values map[string]string `json:"values,omitempty"`
	PostAt *time.Time `json:"postAt,omitempty"`
	RefreshAt time.Time `json:"refreshAt"`
	Visible *bool `json:"visible,omitempty"`
	Flags *int32 `json:"flags,omitempty"`
}

type _UpdateJsonRecord UpdateJsonRecord

// NewUpdateJsonRecord instantiates a new UpdateJsonRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateJsonRecord(id string, parentId string, refreshAt time.Time) *UpdateJsonRecord {
	this := UpdateJsonRecord{}
	this.Id = id
	this.ParentId = parentId
	this.RefreshAt = refreshAt
	return &this
}

// NewUpdateJsonRecordWithDefaults instantiates a new UpdateJsonRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateJsonRecordWithDefaults() *UpdateJsonRecord {
	this := UpdateJsonRecord{}
	var parentId string = "00000000-0000-0000-0000-000000000000"
	this.ParentId = parentId
	return &this
}

// GetId returns the Id field value
func (o *UpdateJsonRecord) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateJsonRecord) SetId(v string) {
	o.Id = v
}

// GetParentId returns the ParentId field value
func (o *UpdateJsonRecord) GetParentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *UpdateJsonRecord) SetParentId(v string) {
	o.ParentId = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateJsonRecord) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateJsonRecord) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateJsonRecord) SetTitle(v string) {
	o.Title = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *UpdateJsonRecord) GetValues() map[string]string {
	if o == nil || IsNil(o.Values) {
		var ret map[string]string
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetValuesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]string{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *UpdateJsonRecord) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]string and assigns it to the Values field.
func (o *UpdateJsonRecord) SetValues(v map[string]string) {
	o.Values = v
}

// GetPostAt returns the PostAt field value if set, zero value otherwise.
func (o *UpdateJsonRecord) GetPostAt() time.Time {
	if o == nil || IsNil(o.PostAt) {
		var ret time.Time
		return ret
	}
	return *o.PostAt
}

// GetPostAtOk returns a tuple with the PostAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetPostAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PostAt) {
		return nil, false
	}
	return o.PostAt, true
}

// HasPostAt returns a boolean if a field has been set.
func (o *UpdateJsonRecord) HasPostAt() bool {
	if o != nil && !IsNil(o.PostAt) {
		return true
	}

	return false
}

// SetPostAt gets a reference to the given time.Time and assigns it to the PostAt field.
func (o *UpdateJsonRecord) SetPostAt(v time.Time) {
	o.PostAt = &v
}

// GetRefreshAt returns the RefreshAt field value
func (o *UpdateJsonRecord) GetRefreshAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RefreshAt
}

// GetRefreshAtOk returns a tuple with the RefreshAt field value
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetRefreshAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshAt, true
}

// SetRefreshAt sets field value
func (o *UpdateJsonRecord) SetRefreshAt(v time.Time) {
	o.RefreshAt = v
}

// GetVisible returns the Visible field value if set, zero value otherwise.
func (o *UpdateJsonRecord) GetVisible() bool {
	if o == nil || IsNil(o.Visible) {
		var ret bool
		return ret
	}
	return *o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetVisibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Visible) {
		return nil, false
	}
	return o.Visible, true
}

// HasVisible returns a boolean if a field has been set.
func (o *UpdateJsonRecord) HasVisible() bool {
	if o != nil && !IsNil(o.Visible) {
		return true
	}

	return false
}

// SetVisible gets a reference to the given bool and assigns it to the Visible field.
func (o *UpdateJsonRecord) SetVisible(v bool) {
	o.Visible = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *UpdateJsonRecord) GetFlags() int32 {
	if o == nil || IsNil(o.Flags) {
		var ret int32
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateJsonRecord) GetFlagsOk() (*int32, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *UpdateJsonRecord) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given int32 and assigns it to the Flags field.
func (o *UpdateJsonRecord) SetFlags(v int32) {
	o.Flags = &v
}

func (o UpdateJsonRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateJsonRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["parentId"] = o.ParentId
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.PostAt) {
		toSerialize["postAt"] = o.PostAt
	}
	toSerialize["refreshAt"] = o.RefreshAt
	if !IsNil(o.Visible) {
		toSerialize["visible"] = o.Visible
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	return toSerialize, nil
}

func (o *UpdateJsonRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"parentId",
		"refreshAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateJsonRecord := _UpdateJsonRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateJsonRecord)

	if err != nil {
		return err
	}

	*o = UpdateJsonRecord(varUpdateJsonRecord)

	return err
}

type NullableUpdateJsonRecord struct {
	value *UpdateJsonRecord
	isSet bool
}

func (v NullableUpdateJsonRecord) Get() *UpdateJsonRecord {
	return v.value
}

func (v *NullableUpdateJsonRecord) Set(val *UpdateJsonRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateJsonRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateJsonRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateJsonRecord(val *UpdateJsonRecord) *NullableUpdateJsonRecord {
	return &NullableUpdateJsonRecord{value: val, isSet: true}
}

func (v NullableUpdateJsonRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateJsonRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


