/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package core

import (
	"encoding/json"
	"time"
)

// checks if the ResourceRecordViewFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRecordViewFilter{}

// ResourceRecordViewFilter struct for ResourceRecordViewFilter
type ResourceRecordViewFilter struct {
	Title *string `json:"title,omitempty"`
	FromTime *time.Time `json:"fromTime,omitempty"`
	FromDate *time.Time `json:"fromDate,omitempty"`
	ToDate *time.Time `json:"toDate,omitempty"`
	WithDisabled *bool `json:"withDisabled,omitempty"`
}

// NewResourceRecordViewFilter instantiates a new ResourceRecordViewFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRecordViewFilter() *ResourceRecordViewFilter {
	this := ResourceRecordViewFilter{}
	return &this
}

// NewResourceRecordViewFilterWithDefaults instantiates a new ResourceRecordViewFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRecordViewFilterWithDefaults() *ResourceRecordViewFilter {
	this := ResourceRecordViewFilter{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ResourceRecordViewFilter) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRecordViewFilter) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ResourceRecordViewFilter) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ResourceRecordViewFilter) SetTitle(v string) {
	o.Title = &v
}

// GetFromTime returns the FromTime field value if set, zero value otherwise.
func (o *ResourceRecordViewFilter) GetFromTime() time.Time {
	if o == nil || IsNil(o.FromTime) {
		var ret time.Time
		return ret
	}
	return *o.FromTime
}

// GetFromTimeOk returns a tuple with the FromTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRecordViewFilter) GetFromTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FromTime) {
		return nil, false
	}
	return o.FromTime, true
}

// HasFromTime returns a boolean if a field has been set.
func (o *ResourceRecordViewFilter) HasFromTime() bool {
	if o != nil && !IsNil(o.FromTime) {
		return true
	}

	return false
}

// SetFromTime gets a reference to the given time.Time and assigns it to the FromTime field.
func (o *ResourceRecordViewFilter) SetFromTime(v time.Time) {
	o.FromTime = &v
}

// GetFromDate returns the FromDate field value if set, zero value otherwise.
func (o *ResourceRecordViewFilter) GetFromDate() time.Time {
	if o == nil || IsNil(o.FromDate) {
		var ret time.Time
		return ret
	}
	return *o.FromDate
}

// GetFromDateOk returns a tuple with the FromDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRecordViewFilter) GetFromDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FromDate) {
		return nil, false
	}
	return o.FromDate, true
}

// HasFromDate returns a boolean if a field has been set.
func (o *ResourceRecordViewFilter) HasFromDate() bool {
	if o != nil && !IsNil(o.FromDate) {
		return true
	}

	return false
}

// SetFromDate gets a reference to the given time.Time and assigns it to the FromDate field.
func (o *ResourceRecordViewFilter) SetFromDate(v time.Time) {
	o.FromDate = &v
}

// GetToDate returns the ToDate field value if set, zero value otherwise.
func (o *ResourceRecordViewFilter) GetToDate() time.Time {
	if o == nil || IsNil(o.ToDate) {
		var ret time.Time
		return ret
	}
	return *o.ToDate
}

// GetToDateOk returns a tuple with the ToDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRecordViewFilter) GetToDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ToDate) {
		return nil, false
	}
	return o.ToDate, true
}

// HasToDate returns a boolean if a field has been set.
func (o *ResourceRecordViewFilter) HasToDate() bool {
	if o != nil && !IsNil(o.ToDate) {
		return true
	}

	return false
}

// SetToDate gets a reference to the given time.Time and assigns it to the ToDate field.
func (o *ResourceRecordViewFilter) SetToDate(v time.Time) {
	o.ToDate = &v
}

// GetWithDisabled returns the WithDisabled field value if set, zero value otherwise.
func (o *ResourceRecordViewFilter) GetWithDisabled() bool {
	if o == nil || IsNil(o.WithDisabled) {
		var ret bool
		return ret
	}
	return *o.WithDisabled
}

// GetWithDisabledOk returns a tuple with the WithDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRecordViewFilter) GetWithDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WithDisabled) {
		return nil, false
	}
	return o.WithDisabled, true
}

// HasWithDisabled returns a boolean if a field has been set.
func (o *ResourceRecordViewFilter) HasWithDisabled() bool {
	if o != nil && !IsNil(o.WithDisabled) {
		return true
	}

	return false
}

// SetWithDisabled gets a reference to the given bool and assigns it to the WithDisabled field.
func (o *ResourceRecordViewFilter) SetWithDisabled(v bool) {
	o.WithDisabled = &v
}

func (o ResourceRecordViewFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRecordViewFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.FromTime) {
		toSerialize["fromTime"] = o.FromTime
	}
	if !IsNil(o.FromDate) {
		toSerialize["fromDate"] = o.FromDate
	}
	if !IsNil(o.ToDate) {
		toSerialize["toDate"] = o.ToDate
	}
	if !IsNil(o.WithDisabled) {
		toSerialize["withDisabled"] = o.WithDisabled
	}
	return toSerialize, nil
}

type NullableResourceRecordViewFilter struct {
	value *ResourceRecordViewFilter
	isSet bool
}

func (v NullableResourceRecordViewFilter) Get() *ResourceRecordViewFilter {
	return v.value
}

func (v *NullableResourceRecordViewFilter) Set(val *ResourceRecordViewFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRecordViewFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRecordViewFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRecordViewFilter(val *ResourceRecordViewFilter) *NullableResourceRecordViewFilter {
	return &NullableResourceRecordViewFilter{value: val, isSet: true}
}

func (v NullableResourceRecordViewFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRecordViewFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


