=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module OpenapiClient
  class JsonRecordControllerApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param new_json_record [NewJsonRecord] 
    # @param [Hash] opts the optional parameters
    # @return [ResourceJsonRecord]
    def create_json_record(new_json_record, opts = {})
      data, _status_code, _headers = create_json_record_with_http_info(new_json_record, opts)
      data
    end

    # @param new_json_record [NewJsonRecord] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ResourceJsonRecord, Integer, Hash)>] ResourceJsonRecord data, response status code and response headers
    def create_json_record_with_http_info(new_json_record, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JsonRecordControllerApi.create_json_record ...'
      end
      # verify the required parameter 'new_json_record' is set
      if @api_client.config.client_side_validation && new_json_record.nil?
        fail ArgumentError, "Missing the required parameter 'new_json_record' when calling JsonRecordControllerApi.create_json_record"
      end
      # resource path
      local_var_path = '/core/api/v2/json-record'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(new_json_record)

      # return_type
      return_type = opts[:debug_return_type] || 'ResourceJsonRecord'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"JsonRecordControllerApi.create_json_record",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JsonRecordControllerApi#create_json_record\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def delete_json_record(id, opts = {})
      delete_json_record_with_http_info(id, opts)
      nil
    end

    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def delete_json_record_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JsonRecordControllerApi.delete_json_record ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling JsonRecordControllerApi.delete_json_record"
      end
      # resource path
      local_var_path = '/core/api/v2/json-record/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"JsonRecordControllerApi.delete_json_record",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JsonRecordControllerApi#delete_json_record\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [ResourceJsonRecord]
    def read_json_record(id, opts = {})
      data, _status_code, _headers = read_json_record_with_http_info(id, opts)
      data
    end

    # @param id [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ResourceJsonRecord, Integer, Hash)>] ResourceJsonRecord data, response status code and response headers
    def read_json_record_with_http_info(id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JsonRecordControllerApi.read_json_record ...'
      end
      # verify the required parameter 'id' is set
      if @api_client.config.client_side_validation && id.nil?
        fail ArgumentError, "Missing the required parameter 'id' when calling JsonRecordControllerApi.read_json_record"
      end
      # resource path
      local_var_path = '/core/api/v2/json-record/{id}'.sub('{' + 'id' + '}', CGI.escape(id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'ResourceJsonRecord'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"JsonRecordControllerApi.read_json_record",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JsonRecordControllerApi#read_json_record\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param update_json_record [UpdateJsonRecord] 
    # @param [Hash] opts the optional parameters
    # @return [ResourceJsonRecord]
    def update_json_record(update_json_record, opts = {})
      data, _status_code, _headers = update_json_record_with_http_info(update_json_record, opts)
      data
    end

    # @param update_json_record [UpdateJsonRecord] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(ResourceJsonRecord, Integer, Hash)>] ResourceJsonRecord data, response status code and response headers
    def update_json_record_with_http_info(update_json_record, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JsonRecordControllerApi.update_json_record ...'
      end
      # verify the required parameter 'update_json_record' is set
      if @api_client.config.client_side_validation && update_json_record.nil?
        fail ArgumentError, "Missing the required parameter 'update_json_record' when calling JsonRecordControllerApi.update_json_record"
      end
      # resource path
      local_var_path = '/core/api/v2/json-record'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['*/*']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(update_json_record)

      # return_type
      return_type = opts[:debug_return_type] || 'ResourceJsonRecord'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"JsonRecordControllerApi.update_json_record",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JsonRecordControllerApi#update_json_record\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
