/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import EntityModelResourceRecordView from './su.svn.lib.core.model/EntityModelResourceRecordView';
import ErrorResponse from './su.svn.lib.core.model/ErrorResponse';
import Link from './su.svn.lib.core.model/Link';
import NewJsonRecord from './su.svn.lib.core.model/NewJsonRecord';
import PageMetadata from './su.svn.lib.core.model/PageMetadata';
import Pageable from './su.svn.lib.core.model/Pageable';
import PagedModelEntityModelResourceRecordView from './su.svn.lib.core.model/PagedModelEntityModelResourceRecordView';
import PagedModelEntityModelResourceRecordViewEmbedded from './su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded';
import ResourceJsonRecord from './su.svn.lib.core.model/ResourceJsonRecord';
import ResourceRecordViewFilter from './su.svn.lib.core.model/ResourceRecordViewFilter';
import UpdateJsonRecord from './su.svn.lib.core.model/UpdateJsonRecord';
import HelloControllerApi from './su.svn.lib.core.api/HelloControllerApi';
import JsonRecordControllerApi from './su.svn.lib.core.api/JsonRecordControllerApi';
import RecordViewControllerApi from './su.svn.lib.core.api/RecordViewControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The EntityModelResourceRecordView model constructor.
     * @property {module:su.svn.lib.core.model/EntityModelResourceRecordView}
     */
    EntityModelResourceRecordView,

    /**
     * The ErrorResponse model constructor.
     * @property {module:su.svn.lib.core.model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The Link model constructor.
     * @property {module:su.svn.lib.core.model/Link}
     */
    Link,

    /**
     * The NewJsonRecord model constructor.
     * @property {module:su.svn.lib.core.model/NewJsonRecord}
     */
    NewJsonRecord,

    /**
     * The PageMetadata model constructor.
     * @property {module:su.svn.lib.core.model/PageMetadata}
     */
    PageMetadata,

    /**
     * The Pageable model constructor.
     * @property {module:su.svn.lib.core.model/Pageable}
     */
    Pageable,

    /**
     * The PagedModelEntityModelResourceRecordView model constructor.
     * @property {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView}
     */
    PagedModelEntityModelResourceRecordView,

    /**
     * The PagedModelEntityModelResourceRecordViewEmbedded model constructor.
     * @property {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordViewEmbedded}
     */
    PagedModelEntityModelResourceRecordViewEmbedded,

    /**
     * The ResourceJsonRecord model constructor.
     * @property {module:su.svn.lib.core.model/ResourceJsonRecord}
     */
    ResourceJsonRecord,

    /**
     * The ResourceRecordViewFilter model constructor.
     * @property {module:su.svn.lib.core.model/ResourceRecordViewFilter}
     */
    ResourceRecordViewFilter,

    /**
     * The UpdateJsonRecord model constructor.
     * @property {module:su.svn.lib.core.model/UpdateJsonRecord}
     */
    UpdateJsonRecord,

    /**
    * The HelloControllerApi service constructor.
    * @property {module:su.svn.lib.core.api/HelloControllerApi}
    */
    HelloControllerApi,

    /**
    * The JsonRecordControllerApi service constructor.
    * @property {module:su.svn.lib.core.api/JsonRecordControllerApi}
    */
    JsonRecordControllerApi,

    /**
    * The RecordViewControllerApi service constructor.
    * @property {module:su.svn.lib.core.api/RecordViewControllerApi}
    */
    RecordViewControllerApi
};
