/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package su.svn.lib.core.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SortObject
 */
public class SortObjectTest {
    private final SortObject model = new SortObject();

    /**
     * Model tests for SortObject
     */
    @Test
    public void testSortObject() {
        // TODO: test SortObject
    }

    /**
     * Test the property 'empty'
     */
    @Test
    public void emptyTest() {
        // TODO: test empty
    }

    /**
     * Test the property 'unsorted'
     */
    @Test
    public void unsortedTest() {
        // TODO: test unsorted
    }

    /**
     * Test the property 'sorted'
     */
    @Test
    public void sortedTest() {
        // TODO: test sorted
    }

}
