=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::JsonRecordControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JsonRecordControllerApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::JsonRecordControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JsonRecordControllerApi' do
    it 'should create an instance of JsonRecordControllerApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::JsonRecordControllerApi)
    end
  end

  # unit tests for create_json_record
  # @param new_json_record 
  # @param [Hash] opts the optional parameters
  # @return [ResourceJsonRecord]
  describe 'create_json_record test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_json_record
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_json_record test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for read_json_record
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ResourceJsonRecord]
  describe 'read_json_record test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_json_record
  # @param update_json_record 
  # @param [Hash] opts the optional parameters
  # @return [ResourceJsonRecord]
  describe 'update_json_record test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
