=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::RecordViewControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecordViewControllerApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::RecordViewControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecordViewControllerApi' do
    it 'should create an instance of RecordViewControllerApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::RecordViewControllerApi)
    end
  end

  # unit tests for get_all_records
  # @param filter 
  # @param pageable 
  # @param [Hash] opts the optional parameters
  # @return [PagedModelEntityModelResourceRecordView]
  describe 'get_all_records test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
