/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../su.svn.lib.core.model/ErrorResponse';
import NewJsonRecord from '../su.svn.lib.core.model/NewJsonRecord';
import ResourceJsonRecord from '../su.svn.lib.core.model/ResourceJsonRecord';
import UpdateJsonRecord from '../su.svn.lib.core.model/UpdateJsonRecord';

/**
* JsonRecordController service.
* @module su.svn.lib.core.api/JsonRecordControllerApi
* @version v0
*/
export default class JsonRecordControllerApi {

    /**
    * Constructs a new JsonRecordControllerApi. 
    * @alias module:su.svn.lib.core.api/JsonRecordControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createJsonRecord operation.
     * @callback module:su.svn.lib.core.api/JsonRecordControllerApi~createJsonRecordCallback
     * @param {String} error Error message, if any.
     * @param {module:su.svn.lib.core.model/ResourceJsonRecord} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:su.svn.lib.core.model/NewJsonRecord} newJsonRecord 
     * @param {module:su.svn.lib.core.api/JsonRecordControllerApi~createJsonRecordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:su.svn.lib.core.model/ResourceJsonRecord}
     */
    createJsonRecord(newJsonRecord, callback) {
      let postBody = newJsonRecord;
      // verify the required parameter 'newJsonRecord' is set
      if (newJsonRecord === undefined || newJsonRecord === null) {
        throw new Error("Missing the required parameter 'newJsonRecord' when calling createJsonRecord");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ResourceJsonRecord;
      return this.apiClient.callApi(
        '/core/api/v2/json-record', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteJsonRecord operation.
     * @callback module:su.svn.lib.core.api/JsonRecordControllerApi~deleteJsonRecordCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:su.svn.lib.core.api/JsonRecordControllerApi~deleteJsonRecordCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteJsonRecord(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteJsonRecord");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = null;
      return this.apiClient.callApi(
        '/core/api/v2/json-record/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the readJsonRecord operation.
     * @callback module:su.svn.lib.core.api/JsonRecordControllerApi~readJsonRecordCallback
     * @param {String} error Error message, if any.
     * @param {module:su.svn.lib.core.model/ResourceJsonRecord} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id 
     * @param {module:su.svn.lib.core.api/JsonRecordControllerApi~readJsonRecordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:su.svn.lib.core.model/ResourceJsonRecord}
     */
    readJsonRecord(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling readJsonRecord");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ResourceJsonRecord;
      return this.apiClient.callApi(
        '/core/api/v2/json-record/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateJsonRecord operation.
     * @callback module:su.svn.lib.core.api/JsonRecordControllerApi~updateJsonRecordCallback
     * @param {String} error Error message, if any.
     * @param {module:su.svn.lib.core.model/ResourceJsonRecord} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:su.svn.lib.core.model/UpdateJsonRecord} updateJsonRecord 
     * @param {module:su.svn.lib.core.api/JsonRecordControllerApi~updateJsonRecordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:su.svn.lib.core.model/ResourceJsonRecord}
     */
    updateJsonRecord(updateJsonRecord, callback) {
      let postBody = updateJsonRecord;
      // verify the required parameter 'updateJsonRecord' is set
      if (updateJsonRecord === undefined || updateJsonRecord === null) {
        throw new Error("Missing the required parameter 'updateJsonRecord' when calling updateJsonRecord");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ResourceJsonRecord;
      return this.apiClient.callApi(
        '/core/api/v2/json-record', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
