/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../su.svn.lib.core.model/ErrorResponse';
import Pageable from '../su.svn.lib.core.model/Pageable';
import PagedModelEntityModelResourceRecordView from '../su.svn.lib.core.model/PagedModelEntityModelResourceRecordView';
import ResourceRecordViewFilter from '../su.svn.lib.core.model/ResourceRecordViewFilter';

/**
* RecordViewController service.
* @module su.svn.lib.core.api/RecordViewControllerApi
* @version v0
*/
export default class RecordViewControllerApi {

    /**
    * Constructs a new RecordViewControllerApi. 
    * @alias module:su.svn.lib.core.api/RecordViewControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllRecords operation.
     * @callback module:su.svn.lib.core.api/RecordViewControllerApi~getAllRecordsCallback
     * @param {String} error Error message, if any.
     * @param {module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:su.svn.lib.core.model/ResourceRecordViewFilter} filter 
     * @param {module:su.svn.lib.core.model/Pageable} pageable 
     * @param {module:su.svn.lib.core.api/RecordViewControllerApi~getAllRecordsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:su.svn.lib.core.model/PagedModelEntityModelResourceRecordView}
     */
    getAllRecords(filter, pageable, callback) {
      let postBody = null;
      // verify the required parameter 'filter' is set
      if (filter === undefined || filter === null) {
        throw new Error("Missing the required parameter 'filter' when calling getAllRecords");
      }
      // verify the required parameter 'pageable' is set
      if (pageable === undefined || pageable === null) {
        throw new Error("Missing the required parameter 'pageable' when calling getAllRecords");
      }

      let pathParams = {
      };
      let queryParams = {
        'filter': filter,
        'pageable': pageable
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PagedModelEntityModelResourceRecordView;
      return this.apiClient.callApi(
        '/core/api/v2/records-view', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
