=begin
#OpenAPI definition

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/api_model_base'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/entity_model_resource_record_view'
require 'openapi_client/models/error_response'
require 'openapi_client/models/link'
require 'openapi_client/models/new_json_record'
require 'openapi_client/models/page_metadata'
require 'openapi_client/models/pageable'
require 'openapi_client/models/paged_model_entity_model_resource_record_view'
require 'openapi_client/models/paged_model_entity_model_resource_record_view_embedded'
require 'openapi_client/models/resource_json_record'
require 'openapi_client/models/resource_record_view_filter'
require 'openapi_client/models/update_json_record'

# APIs
require 'openapi_client/api/hello_controller_api'
require 'openapi_client/api/json_record_controller_api'
require 'openapi_client/api/record_view_controller_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
