# coding: utf-8

# flake8: noqa

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HelloControllerApi",
    "JsonRecordControllerApi",
    "RecordViewControllerApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "EntityModelResourceRecordView",
    "ErrorResponse",
    "Link",
    "NewJsonRecord",
    "PageMetadata",
    "Pageable",
    "PagedModelEntityModelResourceRecordView",
    "PagedModelEntityModelResourceRecordViewEmbedded",
    "ResourceJsonRecord",
    "ResourceRecordViewFilter",
    "UpdateJsonRecord",
]

# import apis into sdk package
from api.hello_controller_api import HelloControllerApi as HelloControllerApi
from api.json_record_controller_api import JsonRecordControllerApi as JsonRecordControllerApi
from api.record_view_controller_api import RecordViewControllerApi as RecordViewControllerApi

# import ApiClient
from core.api_response import ApiResponse as ApiResponse
from core.api_client import ApiClient as ApiClient
from core.configuration import Configuration as Configuration
from core.exceptions import OpenApiException as OpenApiException
from core.exceptions import ApiTypeError as ApiTypeError
from core.exceptions import ApiValueError as ApiValueError
from core.exceptions import ApiKeyError as ApiKeyError
from core.exceptions import ApiAttributeError as ApiAttributeError
from core.exceptions import ApiException as ApiException

# import models into sdk package
from core.model.entity_model_resource_record_view import EntityModelResourceRecordView as EntityModelResourceRecordView
from core.model.error_response import ErrorResponse as ErrorResponse
from core.model.link import Link as Link
from core.model.new_json_record import NewJsonRecord as NewJsonRecord
from core.model.page_metadata import PageMetadata as PageMetadata
from core.model.pageable import Pageable as Pageable
from core.model.paged_model_entity_model_resource_record_view import PagedModelEntityModelResourceRecordView as PagedModelEntityModelResourceRecordView
from core.model.paged_model_entity_model_resource_record_view_embedded import PagedModelEntityModelResourceRecordViewEmbedded as PagedModelEntityModelResourceRecordViewEmbedded
from core.model.resource_json_record import ResourceJsonRecord as ResourceJsonRecord
from core.model.resource_record_view_filter import ResourceRecordViewFilter as ResourceRecordViewFilter
from core.model.update_json_record import UpdateJsonRecord as UpdateJsonRecord

