# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.hello_controller_api import HelloControllerApi


class TestHelloControllerApi(unittest.TestCase):
    """HelloControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelloControllerApi()

    def tearDown(self) -> None:
        pass

    def test_hello(self) -> None:
        """Test case for hello

        """
        pass


if __name__ == '__main__':
    unittest.main()
