# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.json_record_controller_api import JsonRecordControllerApi


class TestJsonRecordControllerApi(unittest.TestCase):
    """JsonRecordControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JsonRecordControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_json_record(self) -> None:
        """Test case for create_json_record

        """
        pass

    def test_delete_json_record(self) -> None:
        """Test case for delete_json_record

        """
        pass

    def test_read_json_record(self) -> None:
        """Test case for read_json_record

        """
        pass

    def test_update_json_record(self) -> None:
        """Test case for update_json_record

        """
        pass


if __name__ == '__main__':
    unittest.main()
