# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.model.new_json_record import NewJsonRecord

class TestNewJsonRecord(unittest.TestCase):
    """NewJsonRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewJsonRecord:
        """Test NewJsonRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewJsonRecord`
        """
        model = NewJsonRecord()
        if include_optional:
            return NewJsonRecord(
                visible = True,
                flags = 56,
                parent_id = '00000000-0000-0000-0000-000000000000',
                title = '',
                values = {
                    'key' : ''
                    },
                post_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NewJsonRecord(
                parent_id = '00000000-0000-0000-0000-000000000000',
                post_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testNewJsonRecord(self):
        """Test NewJsonRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
