# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.model.page_metadata import PageMetadata

class TestPageMetadata(unittest.TestCase):
    """PageMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageMetadata:
        """Test PageMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageMetadata`
        """
        model = PageMetadata()
        if include_optional:
            return PageMetadata(
                size = 56,
                total_elements = 56,
                total_pages = 56,
                number = 56
            )
        else:
            return PageMetadata(
        )
        """

    def testPageMetadata(self):
        """Test PageMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
