# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api.record_view_controller_api import RecordViewControllerApi


class TestRecordViewControllerApi(unittest.TestCase):
    """RecordViewControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordViewControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_records(self) -> None:
        """Test case for get_all_records

        """
        pass


if __name__ == '__main__':
    unittest.main()
