# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.model.update_json_record import UpdateJsonRecord

class TestUpdateJsonRecord(unittest.TestCase):
    """UpdateJsonRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateJsonRecord:
        """Test UpdateJsonRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateJsonRecord`
        """
        model = UpdateJsonRecord()
        if include_optional:
            return UpdateJsonRecord(
                id = '',
                parent_id = '00000000-0000-0000-0000-000000000000',
                title = '',
                var_json = {
                    'key' : ''
                    },
                post_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                refresh_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                visible = True,
                flags = 56,
                tags = [
                    ''
                    ]
            )
        else:
            return UpdateJsonRecord(
                id = '',
                parent_id = '00000000-0000-0000-0000-000000000000',
                refresh_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUpdateJsonRecord(self):
        """Test UpdateJsonRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
