# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.model.entity_model_resource_record_view import EntityModelResourceRecordView

class TestEntityModelResourceRecordView(unittest.TestCase):
    """EntityModelResourceRecordView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityModelResourceRecordView:
        """Test EntityModelResourceRecordView
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityModelResourceRecordView`
        """
        model = EntityModelResourceRecordView()
        if include_optional:
            return EntityModelResourceRecordView(
                id = '',
                visible = True,
                flags = 56,
                parent_id = '',
                user_name = '',
                post_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                refresh_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_changed_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                var_json = {
                    'key' : ''
                    },
                tags = [
                    ''
                    ],
                links = {
                    'key' : core.models.link.Link(
                        href = '', 
                        hreflang = '', 
                        title = '', 
                        type = '', 
                        deprecation = '', 
                        profile = '', 
                        name = '', 
                        templated = True, )
                    }
            )
        else:
            return EntityModelResourceRecordView(
        )
        """

    def testEntityModelResourceRecordView(self):
        """Test EntityModelResourceRecordView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
