// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package session

import (
	"context"
)

//go:generate mockgen -destination=db_mock_test.go -package=session github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/repository/session DBTX

type Repo interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteUserAttrs(ctx context.Context, arg DeleteUserAttrsParams) error
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
}
