// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/resources (interfaces: AuthServiceV2)
//
// Generated by this command:
//
//	mockgen -destination=auth_service_v2_mock_test.go -package=resources github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/resources AuthServiceV2
//

// Package resources is a generated GoMock package.
package resources

import (
	context "context"
	reflect "reflect"

	services "github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/services"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceV2 is a mock of AuthServiceV2 interface.
type MockAuthServiceV2 struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceV2MockRecorder
	isgomock struct{}
}

// MockAuthServiceV2MockRecorder is the mock recorder for MockAuthServiceV2.
type MockAuthServiceV2MockRecorder struct {
	mock *MockAuthServiceV2
}

// NewMockAuthServiceV2 creates a new mock instance.
func NewMockAuthServiceV2(ctrl *gomock.Controller) *MockAuthServiceV2 {
	mock := &MockAuthServiceV2{ctrl: ctrl}
	mock.recorder = &MockAuthServiceV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceV2) EXPECT() *MockAuthServiceV2MockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockAuthServiceV2) Auth(ctx context.Context, login services.Login) (services.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, login)
	ret0, _ := ret[0].(services.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockAuthServiceV2MockRecorder) Auth(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockAuthServiceV2)(nil).Auth), ctx, login)
}

// List mocks base method.
func (m *MockAuthServiceV2) List(ctx context.Context) ([]services.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]services.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuthServiceV2MockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuthServiceV2)(nil).List), ctx)
}

// Logout mocks base method.
func (m *MockAuthServiceV2) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceV2MockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceV2)(nil).Logout), ctx)
}

// Ok mocks base method.
func (m *MockAuthServiceV2) Ok() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ok")
	ret0, _ := ret[0].(string)
	return ret0
}

// Ok indicates an expected call of Ok.
func (mr *MockAuthServiceV2MockRecorder) Ok() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockAuthServiceV2)(nil).Ok))
}

// Refresh mocks base method.
func (m *MockAuthServiceV2) Refresh(ctx context.Context, token string) (services.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, token)
	ret0, _ := ret[0].(services.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthServiceV2MockRecorder) Refresh(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthServiceV2)(nil).Refresh), ctx, token)
}

// Register mocks base method.
func (m *MockAuthServiceV2) Register(ctx context.Context, user services.CreateUser) (services.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(services.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceV2MockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceV2)(nil).Register), ctx, user)
}
