// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/resources (interfaces: AuthServiceV1)
//
// Generated by this command:
//
//	mockgen -destination=auth_service_v1_mock_test.go -package=resources github.com/vskurikhin/DayBook-3.3x/auth/v2/internal/server/resources AuthServiceV1
//

// Package resources is a generated GoMock package.
package resources

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceV1 is a mock of AuthServiceV1 interface.
type MockAuthServiceV1 struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceV1MockRecorder
	isgomock struct{}
}

// MockAuthServiceV1MockRecorder is the mock recorder for MockAuthServiceV1.
type MockAuthServiceV1MockRecorder struct {
	mock *MockAuthServiceV1
}

// NewMockAuthServiceV1 creates a new mock instance.
func NewMockAuthServiceV1(ctrl *gomock.Controller) *MockAuthServiceV1 {
	mock := &MockAuthServiceV1{ctrl: ctrl}
	mock.recorder = &MockAuthServiceV1MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceV1) EXPECT() *MockAuthServiceV1MockRecorder {
	return m.recorder
}

// Ok mocks base method.
func (m *MockAuthServiceV1) Ok() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ok")
	ret0, _ := ret[0].(string)
	return ret0
}

// Ok indicates an expected call of Ok.
func (mr *MockAuthServiceV1MockRecorder) Ok() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockAuthServiceV1)(nil).Ok))
}
