spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: dbuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081

token:
  signing:
    key: Y2Q4ZjVmOWYtZTNlOC01NjlmLTg3ZWYtZjAzYzZjZmMyOWJj
